#include <QStandardPaths>

#include <TpApplication>
#include <TpColorScheme>
#include <TpFontScheme>

TP_NAMESPACE

void TpApplication::initOtherSettings()
{
    DEF_SETTINGS;

    INIT_SETTINGS("App/CurrentDirectory",
                  QStandardPaths::standardLocations(QStandardPaths::StandardLocation::DocumentsLocation).at(0));
    INIT_SETTINGS("App/Geometry", "");
    settings.setValue("App/Editors", settings.value("App/Editors", QMap<QString, QVariant>{}));
    settings.setValue("App/EditorSettings", settings.value("App/EditorSettings", QMap<QString, QVariant>{}));
    INIT_SETTINGS("App/BrowserDirectory", QString());

    INIT_SETTINGS("View/ShowSymbols/SpacesAndTabsAll", false);
    INIT_SETTINGS("View/ShowSymbols/SpacesAndTabsAfterIndentation", false);
    INIT_SETTINGS("View/ShowSymbols/SpacesAndTabsInIndentation", false);
    INIT_SETTINGS("View/ShowSymbols/NonPrintable", false);
    INIT_SETTINGS("View/ShowSymbols/WrapVisualFlags", false);
    INIT_SETTINGS("View/ShowSymbols/IndentationGuides", true);
    INIT_SETTINGS("View/WordWrap/None", true);
    INIT_SETTINGS("View/WordWrap/Word", false);
    INIT_SETTINGS("View/WordWrap/Character", false);
    INIT_SETTINGS("View/WordWrap/Whitespace", false);
    INIT_SETTINGS("View/LineNumbers", true);
    INIT_SETTINGS("View/Folding/DisableFolding", false);
    INIT_SETTINGS("View/Folding/Plain", true);
    INIT_SETTINGS("View/Folding/Circled", false);
    INIT_SETTINGS("View/Folding/Boxed", false);
    INIT_SETTINGS("View/Folding/CircledTree", false);
    INIT_SETTINGS("View/Folding/BoxedTree", false);
    INIT_SETTINGS("Format/Newline/UseWindows", false);
    INIT_SETTINGS("Format/Newline/UseClassicalMac", false);
    INIT_SETTINGS("Format/Newline/UseUnix", true);
    INIT_SETTINGS("Format/Indentation/UseTabsToIndent", false);
    INIT_SETTINGS("Format/Indentation/BackspaceUnindents", true);
    INIT_SETTINGS("Format/Indentation/TabToIndent", true);
    INIT_SETTINGS("Format/RepresentingTabs/LongArrow", true);
    INIT_SETTINGS("Format/RepresentingTabs/StrikeOut", false);
    INIT_SETTINGS("Format/SelectFirstWrappedLineOnly", false);
    INIT_SETTINGS("Tools/Autocompletion/CaseSensitive", false);
    INIT_SETTINGS("Tools/Autocompletion/FillupsEnabled", true);
    INIT_SETTINGS("Tools/Autocompletion/ReplaceWord", true);
    INIT_SETTINGS("Tools/Autocompletion/WhenSingleEntry/DoNotDisplay", false);
    INIT_SETTINGS("Tools/Autocompletion/WhenSingleEntry/OnlyManually", true);
    INIT_SETTINGS("Tools/Autocompletion/WhenSingleEntry/AlwaysDisplay", false);
    INIT_SETTINGS("Tools/Autocompletion/Sources/DoNotDisplay", false);
    INIT_SETTINGS("Tools/Autocompletion/Sources/All", true);
    INIT_SETTINGS("Tools/Autocompletion/Sources/Document", false);
    INIT_SETTINGS("Tools/Autocompletion/Sources/Lexer", false);
    INIT_SETTINGS("Tools/Autoindentation/Autoindentation", true);
    INIT_SETTINGS("Tools/Autoindentation/Style/Auto", true);
    INIT_SETTINGS("Tools/Autoindentation/Style/Maintain", false);
    INIT_SETTINGS("Tools/Autoindentation/Style/Opening", false);
    INIT_SETTINGS("Tools/Autoindentation/Style/Closing", false);
    INIT_SETTINGS("Tools/BraceMatching/NoBraceMatching", false);
    INIT_SETTINGS("Tools/BraceMatching/SloppyBraceMatch", true);
    INIT_SETTINGS("Tools/BraceMatching/StrictBraceMatch", false);
    INIT_SETTINGS("Tools/BraceMatching/AutoInsert/Brackets", true);
    INIT_SETTINGS("Tools/BraceMatching/AutoInsert/BracesOnNewlines", true);
    INIT_SETTINGS("Tools/BraceMatching/AutoInsert/BracketsAndQuotesWithinSelection", true);
    INIT_SETTINGS("Tools/BraceMatching/AutoDelete/BracketsAndQuotes", true);
    INIT_SETTINGS("Tools/CallTips/Position/BelowText", false);
    INIT_SETTINGS("Tools/CallTips/Position/AboveText", true);
    INIT_SETTINGS("Tools/CallTips/Style/DisableCallTips", false);
    INIT_SETTINGS("Tools/CallTips/Style/NoContextOrScope", false);
    INIT_SETTINGS("Tools/CallTips/Style/NoAutocompletionContext", false);
    INIT_SETTINGS("Tools/CallTips/Style/WithAllContext", true);
    INIT_SETTINGS("Tools/EdgeMode/None", true);
    INIT_SETTINGS("Tools/EdgeMode/Line", false);
    INIT_SETTINGS("Tools/EdgeMode/Background", false);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/SelectionTillBorder", true);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/MultipleSelection", true);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/AdditionalSelectionTyping", true);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/MultiplePaste", true);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/VirtualSpace/Disabled", false);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/VirtualSpace/OnRectangularSelections", true);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/VirtualSpace/UsersAccessible", false);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/VirtualSpace/NoWrapLineStart", false);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/RectangularSelectionModifier/CTRL", false);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/RectangularSelectionModifier/ALT", true);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/CaretSticky/Off", true);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/CaretSticky/On", false);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/CaretSticky/WithWhitespacesOnly", false);
    INIT_SETTINGS("Tools/CaretAndVirtualSelection/CaretLineVisible", true);
    INIT_SETTINGS("Tools/Search/RegularExpression/No", false);
    INIT_SETTINGS("Tools/Search/RegularExpression/Simple", true);
    INIT_SETTINGS("Tools/Search/RegularExpression/POSIX", false);
    INIT_SETTINGS("Tools/Search/RegularExpression/C++", false);
    INIT_SETTINGS("Tools/Search/Casesensitive", false);
    INIT_SETTINGS("Tools/Search/WholeWordOnly", false);
    INIT_SETTINGS("Tools/Search/WordWrap", true);
    INIT_SETTINGS("Tools/Search/Show", true);
    INIT_SETTINGS("Tools/Search/GoPrevious", false);
    INIT_SETTINGS("Tools/WrappingTools/Indentation/Predefined", true);
    INIT_SETTINGS("Tools/WrappingTools/Indentation/SameAsFirstSubline", false);
    INIT_SETTINGS("Tools/WrappingTools/Indentation/Indented", false);
    INIT_SETTINGS("Tools/WrappingTools/Indentation/Doubleindented", false);
    INIT_SETTINGS("Tools/WrappingTools/StartFlag/None", true);
    INIT_SETTINGS("Tools/WrappingTools/StartFlag/ByText", false);
    INIT_SETTINGS("Tools/WrappingTools/StartFlag/ByBorder", false);
    INIT_SETTINGS("Tools/WrappingTools/StartFlag/InMargin", false);
    INIT_SETTINGS("Tools/WrappingTools/EndFlag/None", true);
    INIT_SETTINGS("Tools/WrappingTools/EndFlag/ByText", false);
    INIT_SETTINGS("Tools/WrappingTools/EndFlag/ByBorder", false);
    INIT_SETTINGS("Tools/WrappingTools/EndFlag/InMargin", false);
    INIT_SETTINGS("Tools/Miscellaneous/BufferedDraw", false);
    INIT_SETTINGS("Tools/Miscellaneous/PhaseDraw/PhaseOne", false);
    INIT_SETTINGS("Tools/Miscellaneous/PhaseDraw/PhaseTwo", true);
    INIT_SETTINGS("Tools/Miscellaneous/PhaseDraw/PhaseMultiple", false);
    INIT_SETTINGS("Tools/Miscellaneous/FontQuality/Default", true);
    INIT_SETTINGS("Tools/Miscellaneous/FontQuality/Nonantialized", false);
    INIT_SETTINGS("Tools/Miscellaneous/FontQuality/Antialized", false);
    INIT_SETTINGS("Tools/Miscellaneous/FontQuality/LCDOptimized", false);
    INIT_SETTINGS("Windows/FileBrowser", false);
    INIT_SETTINGS("Windows/DocumentList", false);
    INIT_SETTINGS("Windows/Bookmarks", false);
    INIT_SETTINGS("Windows/FindDock", false);
    INIT_SETTINGS("Windows/FindInFilesDock", false);
    INIT_SETTINGS("Windows/QSSViewer", false);
    INIT_SETTINGS("Windows/StatusBar", true);

    INIT_SETTINGS("Editor/Values/AutoCompletionThreshold", 1);
    INIT_SETTINGS("Editor/Values/CallTipsMaximum", -1);
    INIT_SETTINGS("Editor/Values/CaretLineWidth", 3);
    INIT_SETTINGS("Editor/Values/EdgeColumn", 120);
    INIT_SETTINGS("Editor/Values/ExtraAscent", 2);
    INIT_SETTINGS("Editor/Values/ExtraDescent", 2);
    INIT_SETTINGS("Editor/Values/TabWidth", 4);

    INIT_SETTINGS("Editor/Color/Universal", defaultColorScheme->Default);
    INIT_SETTINGS("Editor/Color/Comment", defaultColorScheme->Comment);
    INIT_SETTINGS("Editor/Color/CommentLine", defaultColorScheme->CommentLine);
    INIT_SETTINGS("Editor/Color/CommentDoc", defaultColorScheme->CommentDoc);
    INIT_SETTINGS("Editor/Color/Number", defaultColorScheme->Number);
    INIT_SETTINGS("Editor/Color/Keyword", defaultColorScheme->Keyword);
    INIT_SETTINGS("Editor/Color/DoubleQuotedString", defaultColorScheme->DoubleQuotedString);
    INIT_SETTINGS("Editor/Color/SingleQuotedString", defaultColorScheme->SingleQuotedString);
    INIT_SETTINGS("Editor/Color/UUID", defaultColorScheme->UUID);
    INIT_SETTINGS("Editor/Color/PreProcessor", defaultColorScheme->PreProcessor);
    INIT_SETTINGS("Editor/Color/Operator", defaultColorScheme->Operator);
    INIT_SETTINGS("Editor/Color/Identifier", defaultColorScheme->Identifier);
    INIT_SETTINGS("Editor/Color/UnclosedString", defaultColorScheme->UnclosedString);
    INIT_SETTINGS("Editor/Color/VerbatimString", defaultColorScheme->VerbatimString);
    INIT_SETTINGS("Editor/Color/Regex", defaultColorScheme->Regex);
    INIT_SETTINGS("Editor/Color/CommentLineDoc", defaultColorScheme->CommentLineDoc);
    INIT_SETTINGS("Editor/Color/KeywordSet2", defaultColorScheme->KeywordSet2);
    INIT_SETTINGS("Editor/Color/CommentDocKeyword", defaultColorScheme->CommentDocKeyword);
    INIT_SETTINGS("Editor/Color/CommentDocKeywordError", defaultColorScheme->CommentDocKeywordError);
    INIT_SETTINGS("Editor/Color/GlobalClass", defaultColorScheme->GlobalClass);
    INIT_SETTINGS("Editor/Color/RawString", defaultColorScheme->RawString);
    INIT_SETTINGS("Editor/Color/TripleQuotedVerbatimString", defaultColorScheme->TripleQuotedVerbatimString);
    INIT_SETTINGS("Editor/Color/HashQuotedString", defaultColorScheme->HashQuotedString);
    INIT_SETTINGS("Editor/Color/PreProcessorComment", defaultColorScheme->PreProcessorComment);
    INIT_SETTINGS("Editor/Color/PreProcessorCommentLineDoc", defaultColorScheme->PreProcessorCommentLineDoc);
    INIT_SETTINGS("Editor/Color/UserLiteral", defaultColorScheme->UserLiteral);
    INIT_SETTINGS("Editor/Color/TaskMarker", defaultColorScheme->TaskMarker);
    INIT_SETTINGS("Editor/Color/EscapeSequence", defaultColorScheme->EscapeSequence);
    INIT_SETTINGS("Editor/Color/InactiveDefault", defaultColorScheme->InactiveDefault);
    INIT_SETTINGS("Editor/Color/InactiveComment", defaultColorScheme->InactiveComment);
    INIT_SETTINGS("Editor/Color/InactiveCommentLine", defaultColorScheme->InactiveCommentLine);
    INIT_SETTINGS("Editor/Color/InactiveCommentDoc", defaultColorScheme->InactiveCommentDoc);
    INIT_SETTINGS("Editor/Color/InactiveNumber", defaultColorScheme->InactiveNumber);
    INIT_SETTINGS("Editor/Color/InactiveKeyword", defaultColorScheme->InactiveKeyword);
    INIT_SETTINGS("Editor/Color/InactiveDoubleQuotedString", defaultColorScheme->InactiveDoubleQuotedString);
    INIT_SETTINGS("Editor/Color/InactiveSingleQuotedString", defaultColorScheme->InactiveSingleQuotedString);
    INIT_SETTINGS("Editor/Color/InactiveUUID", defaultColorScheme->InactiveUUID);
    INIT_SETTINGS("Editor/Color/InactivePreProcessor", defaultColorScheme->InactivePreProcessor);
    INIT_SETTINGS("Editor/Color/InactiveOperator", defaultColorScheme->InactiveOperator);
    INIT_SETTINGS("Editor/Color/InactiveIdentifier", defaultColorScheme->InactiveIdentifier);
    INIT_SETTINGS("Editor/Color/InactiveUnclosedString", defaultColorScheme->InactiveUnclosedString);
    INIT_SETTINGS("Editor/Color/InactiveVerbatimString", defaultColorScheme->InactiveVerbatimString);
    INIT_SETTINGS("Editor/Color/InactiveRegex", defaultColorScheme->InactiveRegex);
    INIT_SETTINGS("Editor/Color/InactiveCommentLineDoc", defaultColorScheme->InactiveCommentLineDoc);
    INIT_SETTINGS("Editor/Color/InactiveKeywordSet2", defaultColorScheme->InactiveKeywordSet2);
    INIT_SETTINGS("Editor/Color/InactiveCommentDocKeyword", defaultColorScheme->InactiveCommentDocKeyword);
    INIT_SETTINGS("Editor/Color/InactiveCommentDocKeywordError", defaultColorScheme->InactiveCommentDocKeywordError);
    INIT_SETTINGS("Editor/Color/InactiveGlobalClass", defaultColorScheme->InactiveGlobalClass);
    INIT_SETTINGS("Editor/Color/InactiveRawString", defaultColorScheme->InactiveRawString);
    INIT_SETTINGS("Editor/Color/InactiveTripleQuotedVerbatimString",
                  defaultColorScheme->InactiveTripleQuotedVerbatimString);
    INIT_SETTINGS("Editor/Color/InactiveHashQuotedString", defaultColorScheme->InactiveHashQuotedString);
    INIT_SETTINGS("Editor/Color/InactivePreProcessorComment", defaultColorScheme->InactivePreProcessorComment);
    INIT_SETTINGS("Editor/Color/InactivePreProcessorCommentLineDoc",
                  defaultColorScheme->InactivePreProcessorCommentLineDoc);
    INIT_SETTINGS("Editor/Color/InactiveUserLiteral", defaultColorScheme->InactiveUserLiteral);
    INIT_SETTINGS("Editor/Color/InactiveTaskMarker", defaultColorScheme->InactiveTaskMarker);
    INIT_SETTINGS("Editor/Color/InactiveEscapeSequence", defaultColorScheme->InactiveEscapeSequence);
    INIT_SETTINGS("Editor/Color/Error", defaultColorScheme->Error);
    INIT_SETTINGS("Editor/Color/Type", defaultColorScheme->Type);
    INIT_SETTINGS("Editor/Color/PrimitiveType", defaultColorScheme->PrimitiveType);
    INIT_SETTINGS("Editor/Color/Warning", defaultColorScheme->Warning);
    INIT_SETTINGS("Editor/Color/WeakWarning", defaultColorScheme->WeakWarning);
    INIT_SETTINGS("Editor/BgColor/Universal", defaultColorScheme->BgDefault);
    INIT_SETTINGS("Editor/BgColor/Comment", defaultColorScheme->BgComment);
    INIT_SETTINGS("Editor/BgColor/CommentLine", defaultColorScheme->BgCommentLine);
    INIT_SETTINGS("Editor/BgColor/CommentDoc", defaultColorScheme->BgCommentDoc);
    INIT_SETTINGS("Editor/BgColor/Number", defaultColorScheme->BgNumber);
    INIT_SETTINGS("Editor/BgColor/Keyword", defaultColorScheme->BgKeyword);
    INIT_SETTINGS("Editor/BgColor/DoubleQuotedString", defaultColorScheme->BgDoubleQuotedString);
    INIT_SETTINGS("Editor/BgColor/SingleQuotedString", defaultColorScheme->BgSingleQuotedString);
    INIT_SETTINGS("Editor/BgColor/UUID", defaultColorScheme->BgUUID);
    INIT_SETTINGS("Editor/BgColor/PreProcessor", defaultColorScheme->BgPreProcessor);
    INIT_SETTINGS("Editor/BgColor/Operator", defaultColorScheme->BgOperator);
    INIT_SETTINGS("Editor/BgColor/Identifier", defaultColorScheme->BgIdentifier);
    INIT_SETTINGS("Editor/BgColor/UnclosedString", defaultColorScheme->BgUnclosedString);
    INIT_SETTINGS("Editor/BgColor/VerbatimString", defaultColorScheme->BgVerbatimString);
    INIT_SETTINGS("Editor/BgColor/Regex", defaultColorScheme->BgRegex);
    INIT_SETTINGS("Editor/BgColor/CommentLineDoc", defaultColorScheme->BgCommentLineDoc);
    INIT_SETTINGS("Editor/BgColor/KeywordSet2", defaultColorScheme->BgKeywordSet2);
    INIT_SETTINGS("Editor/BgColor/CommentDocKeyword", defaultColorScheme->BgCommentDocKeyword);
    INIT_SETTINGS("Editor/BgColor/CommentDocKeywordError", defaultColorScheme->BgCommentDocKeywordError);
    INIT_SETTINGS("Editor/BgColor/GlobalClass", defaultColorScheme->BgGlobalClass);
    INIT_SETTINGS("Editor/BgColor/RawString", defaultColorScheme->BgRawString);
    INIT_SETTINGS("Editor/BgColor/TripleQuotedVerbatimString", defaultColorScheme->BgTripleQuotedVerbatimString);
    INIT_SETTINGS("Editor/BgColor/HashQuotedString", defaultColorScheme->BgHashQuotedString);
    INIT_SETTINGS("Editor/BgColor/PreProcessorComment", defaultColorScheme->BgPreProcessorComment);
    INIT_SETTINGS("Editor/BgColor/PreProcessorCommentLineDoc", defaultColorScheme->BgPreProcessorCommentLineDoc);
    INIT_SETTINGS("Editor/BgColor/UserLiteral", defaultColorScheme->BgUserLiteral);
    INIT_SETTINGS("Editor/BgColor/TaskMarker", defaultColorScheme->BgTaskMarker);
    INIT_SETTINGS("Editor/BgColor/EscapeSequence", defaultColorScheme->BgEscapeSequence);
    INIT_SETTINGS("Editor/BgColor/InactiveDefault", defaultColorScheme->BgInactiveDefault);
    INIT_SETTINGS("Editor/BgColor/InactiveComment", defaultColorScheme->BgInactiveComment);
    INIT_SETTINGS("Editor/BgColor/InactiveCommentLine", defaultColorScheme->BgInactiveCommentLine);
    INIT_SETTINGS("Editor/BgColor/InactiveCommentDoc", defaultColorScheme->BgInactiveCommentDoc);
    INIT_SETTINGS("Editor/BgColor/InactiveNumber", defaultColorScheme->BgInactiveNumber);
    INIT_SETTINGS("Editor/BgColor/InactiveKeyword", defaultColorScheme->BgInactiveKeyword);
    INIT_SETTINGS("Editor/BgColor/InactiveDoubleQuotedString", defaultColorScheme->BgInactiveDoubleQuotedString);
    INIT_SETTINGS("Editor/BgColor/InactiveSingleQuotedString", defaultColorScheme->BgInactiveSingleQuotedString);
    INIT_SETTINGS("Editor/BgColor/InactiveUUID", defaultColorScheme->BgInactiveUUID);
    INIT_SETTINGS("Editor/BgColor/InactivePreProcessor", defaultColorScheme->BgInactivePreProcessor);
    INIT_SETTINGS("Editor/BgColor/InactiveOperator", defaultColorScheme->BgInactiveOperator);
    INIT_SETTINGS("Editor/BgColor/InactiveIdentifier", defaultColorScheme->BgInactiveIdentifier);
    INIT_SETTINGS("Editor/BgColor/InactiveUnclosedString", defaultColorScheme->BgInactiveUnclosedString);
    INIT_SETTINGS("Editor/BgColor/InactiveVerbatimString", defaultColorScheme->BgInactiveVerbatimString);
    INIT_SETTINGS("Editor/BgColor/InactiveRegex", defaultColorScheme->BgInactiveRegex);
    INIT_SETTINGS("Editor/BgColor/InactiveCommentLineDoc", defaultColorScheme->BgInactiveCommentLineDoc);
    INIT_SETTINGS("Editor/BgColor/InactiveKeywordSet2", defaultColorScheme->BgInactiveKeywordSet2);
    INIT_SETTINGS("Editor/BgColor/InactiveCommentDocKeyword", defaultColorScheme->BgInactiveCommentDocKeyword);
    INIT_SETTINGS("Editor/BgColor/InactiveCommentDocKeywordError",
                  defaultColorScheme->BgInactiveCommentDocKeywordError);
    INIT_SETTINGS("Editor/BgColor/InactiveGlobalClass", defaultColorScheme->BgInactiveGlobalClass);
    INIT_SETTINGS("Editor/BgColor/InactiveRawString", defaultColorScheme->BgInactiveRawString);
    INIT_SETTINGS("Editor/BgColor/InactiveTripleQuotedVerbatimString",
                  defaultColorScheme->BgInactiveTripleQuotedVerbatimString);
    INIT_SETTINGS("Editor/BgColor/InactiveHashQuotedString", defaultColorScheme->BgInactiveHashQuotedString);
    INIT_SETTINGS("Editor/BgColor/InactivePreProcessorComment", defaultColorScheme->BgInactivePreProcessorComment);
    INIT_SETTINGS("Editor/BgColor/InactivePreProcessorCommentLineDoc",
                  defaultColorScheme->BgInactivePreProcessorCommentLineDoc);
    INIT_SETTINGS("Editor/BgColor/InactiveUserLiteral", defaultColorScheme->BgInactiveUserLiteral);
    INIT_SETTINGS("Editor/BgColor/InactiveTaskMarker", defaultColorScheme->BgInactiveTaskMarker);
    INIT_SETTINGS("Editor/BgColor/InactiveEscapeSequence", defaultColorScheme->BgInactiveEscapeSequence);
    INIT_SETTINGS("Editor/BgColor/Error", defaultColorScheme->BgError);
    INIT_SETTINGS("Editor/BgColor/Type", defaultColorScheme->BgType);
    INIT_SETTINGS("Editor/BgColor/PrimitiveType", defaultColorScheme->BgPrimitiveType);
    INIT_SETTINGS("Editor/BgColor/Warning", defaultColorScheme->BgWarning);
    INIT_SETTINGS("Editor/BgColor/WeakWarning", defaultColorScheme->BgWeakWarning);

    INIT_SETTINGS("Editor/Color/Caret", defaultColorScheme->Caret);
    INIT_SETTINGS("Editor/BgColor/Caret", defaultColorScheme->BgCaret);
    INIT_SETTINGS("Editor/Color/IndentationGuides", defaultColorScheme->IndentationGuides);
    INIT_SETTINGS("Editor/BgColor/IndentationGuides", defaultColorScheme->BgIndentationGuides);
    INIT_SETTINGS("Editor/Color/Margin", defaultColorScheme->Margin);
    INIT_SETTINGS("Editor/BgColor/Margin", defaultColorScheme->BgMargin);
    INIT_SETTINGS("Editor/Color/Selection", defaultColorScheme->Selection);
    INIT_SETTINGS("Editor/BgColor/Selection", defaultColorScheme->BgSelection);
}

TP_END_NAMESPACE
