#include <Widgets/TpGeneralComboBox>
#include <TpApplication>
#include <TpMainWindow>
#include <TpTabSplitter>

TP_NAMESPACE

void TpMainWindow::connectSignals()
{
    connect(qobject_cast<TpApplication*>(qApp),
            &TpApplication::messageReceived,
            this,
            &TpMainWindow::onAppMessageReceived);

    connect(m_menuBar->F_N_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_N_T);
    connect(m_menuBar->F_N_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_N_W);
    connect(m_menuBar->F_O_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_O_T);
    connect(m_menuBar->F_O_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_O_W);

    for (auto &action : m_menuBar->m_recentFileActions)
        connect(action,
                &TpGeneralAction::triggered,
                this,
                &TpMainWindow::onAction_F_R);

    connect(m_menuBar->F_R_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_R_C);
    connect(m_menuBar->F_R_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_R_O);
    connect(m_menuBar->F_R_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_R_L);
    connect(m_menuBar->F_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_U);
    connect(m_menuBar->F_T_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_T_F);
    connect(m_menuBar->F_T_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_T_C);
    connect(m_menuBar->F_T_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_T_T);
    connect(m_menuBar->F_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_E);
    connect(m_menuBar->F_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_D);
    connect(m_menuBar->F_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_W);
    connect(m_menuBar->F_B_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_B_R);
    connect(m_menuBar->F_B_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_B_D);
    connect(m_menuBar->F_B_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_B_F);
    connect(m_menuBar->F_B_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_B_A);
    connect(m_menuBar->F_B_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_B_N);
    connect(m_menuBar->F_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_S);
    connect(m_menuBar->F_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_A);
    connect(m_menuBar->F_Y,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_Y);
    connect(m_menuBar->F_d,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_d);
    connect(m_menuBar->F_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_C);
    connect(m_menuBar->F_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_L);
    connect(m_menuBar->F_p,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_p);
    connect(m_menuBar->F_M_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_M_B);
    connect(m_menuBar->F_M_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_M_L);
    connect(m_menuBar->F_M_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_M_R);
    connect(m_menuBar->F_M_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_M_U);
    connect(m_menuBar->F_Q,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_F_Q);
    connect(m_menuBar->E_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_U);
    connect(m_menuBar->E_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_R);
    connect(m_menuBar->E_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_C);
    connect(m_menuBar->E_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_O);
    connect(m_menuBar->E_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_P);
    connect(m_menuBar->E_D_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_D_D);
    connect(m_menuBar->E_D_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_D_B);
    connect(m_menuBar->E_D_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_D_I);
    connect(m_menuBar->E_D_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_D_L);
    connect(m_menuBar->E_D_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_D_R);
    connect(m_menuBar->E_D_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_D_E);
    connect(m_menuBar->E_D_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_D_N);
    connect(m_menuBar->E_M_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_A);
    connect(m_menuBar->E_M_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_B);
    connect(m_menuBar->E_M_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_C);
    connect(m_menuBar->E_M_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_D);
    connect(m_menuBar->E_M_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_E);
    connect(m_menuBar->E_M_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_F);
    connect(m_menuBar->E_M_G,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_G);
    connect(m_menuBar->E_M_H,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_H);
    connect(m_menuBar->E_M_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_I);
    connect(m_menuBar->E_M_J,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_J);
    connect(m_menuBar->E_M_K,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_K);
    connect(m_menuBar->E_M_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_L);
    connect(m_menuBar->E_M_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_M);
    connect(m_menuBar->E_M_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_N);
    connect(m_menuBar->E_M_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_O);
    connect(m_menuBar->E_M_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_P);
    connect(m_menuBar->E_M_Q,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_Q);
    connect(m_menuBar->E_M_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_R);
    connect(m_menuBar->E_M_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_S);
    connect(m_menuBar->E_M_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_T);
    connect(m_menuBar->E_M_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_U);
    connect(m_menuBar->E_M_V,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_V);
    connect(m_menuBar->E_M_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_W);
    connect(m_menuBar->E_M_X,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_X);
    connect(m_menuBar->E_M_Y,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_Y);
    connect(m_menuBar->E_M_Z,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_M_Z);
    connect(m_menuBar->E_S_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_A);
    connect(m_menuBar->E_S_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_B);
    connect(m_menuBar->E_S_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_C);
    connect(m_menuBar->E_S_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_D);
    connect(m_menuBar->E_S_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_E);
    connect(m_menuBar->E_S_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_F);
    connect(m_menuBar->E_S_G,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_G);
    connect(m_menuBar->E_S_H,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_H);
    connect(m_menuBar->E_S_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_I);
    connect(m_menuBar->E_S_J,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_J);
    connect(m_menuBar->E_S_K,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_K);
    connect(m_menuBar->E_S_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_L);
    connect(m_menuBar->E_S_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_M);
    connect(m_menuBar->E_S_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_N);
    connect(m_menuBar->E_S_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_O);
    connect(m_menuBar->E_S_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_P);
    connect(m_menuBar->E_S_Q,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_Q);
    connect(m_menuBar->E_S_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_R);
    connect(m_menuBar->E_S_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_S);
    connect(m_menuBar->E_S_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_T);
    connect(m_menuBar->E_S_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_U);
    connect(m_menuBar->E_S_V,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_V);
    connect(m_menuBar->E_S_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_W);
    connect(m_menuBar->E_S_X,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_X);
    connect(m_menuBar->E_S_Y,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_Y);
    connect(m_menuBar->E_S_Z,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_S_Z);
    connect(m_menuBar->E_I_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_I_I);
    connect(m_menuBar->E_I_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_I_D);
    connect(m_menuBar->E_L_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_D);
    connect(m_menuBar->E_L_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_C);
    connect(m_menuBar->E_L_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_O);
    connect(m_menuBar->E_L_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_T);
    connect(m_menuBar->E_L_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_U);
    connect(m_menuBar->E_L_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_W);
    connect(m_menuBar->E_L_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_R);
    connect(m_menuBar->E_L_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_N);
    connect(m_menuBar->E_L_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_E);
    connect(m_menuBar->E_L_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_B);
    connect(m_menuBar->E_L_V,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_V);
    connect(m_menuBar->E_L_Z,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_L_Z);
    connect(m_menuBar->E_W_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_W_T);
    connect(m_menuBar->E_W_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_W_L);
    connect(m_menuBar->E_W_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_W_B);
    connect(m_menuBar->E_W_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_W_S);
    connect(m_menuBar->E_W_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_W_P);
    connect(m_menuBar->E_W_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_W_A);
    connect(m_menuBar->E_A_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_A_L);
    connect(m_menuBar->E_A_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_A_S);
    connect(m_menuBar->E_G,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_G);
    connect(m_menuBar->E_E_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_E_F);
    connect(m_menuBar->E_E_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_E_N);
    connect(m_menuBar->E_E_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_E_P);
    connect(m_menuBar->E_E_X,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_E_X);
    connect(m_menuBar->E_E_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_E_U);
    connect(m_menuBar->E_E_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_E_L);
    connect(m_menuBar->E_E_G,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_E_G);
    connect(m_menuBar->E_E_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_E_M);
    connect(m_menuBar->E_E_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_E_S);
    connect(m_menuBar->E_B_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_B_T);
    connect(m_menuBar->E_B_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_B_N);
    connect(m_menuBar->E_B_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_B_P);
    connect(m_menuBar->E_B_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_B_C);
    connect(m_menuBar->E_B_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_B_O);
    connect(m_menuBar->E_B_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_B_R);
    connect(m_menuBar->E_B_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_B_A);
    connect(m_menuBar->E_B_h,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_B_h);
    connect(m_menuBar->E_B_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_E_B_I);
    connect(m_menuBar->V_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_A);
    connect(m_menuBar->V_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_F);
    connect(m_menuBar->V_h,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_h);
    connect(m_menuBar->V_Y_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_Y_S);
    connect(m_menuBar->V_Y_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_Y_A);
    connect(m_menuBar->V_Y_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_Y_T);
    connect(m_menuBar->V_Y_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_Y_N);
    connect(m_menuBar->V_Y_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_Y_W);
    connect(m_menuBar->V_Y_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_Y_I);
    connect(m_menuBar->V_Z_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_Z_I);
    connect(m_menuBar->V_Z_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_Z_O);
    connect(m_menuBar->V_Z_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_Z_T);
    connect(m_menuBar->V_T_1,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_1);
    connect(m_menuBar->V_T_2,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_2);
    connect(m_menuBar->V_T_3,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_3);
    connect(m_menuBar->V_T_4,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_4);
    connect(m_menuBar->V_T_5,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_5);
    connect(m_menuBar->V_T_6,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_6);
    connect(m_menuBar->V_T_7,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_7);
    connect(m_menuBar->V_T_8,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_8);
    connect(m_menuBar->V_T_9,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_9);
    connect(m_menuBar->V_T_0,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_0);
    connect(m_menuBar->V_T_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_L);
    connect(m_menuBar->V_T_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_N);
    connect(m_menuBar->V_T_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_F);
    connect(m_menuBar->V_T_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_P);
    connect(m_menuBar->V_T_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_M);
    connect(m_menuBar->V_T_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_R);
    connect(m_menuBar->V_T_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_S);
    connect(m_menuBar->V_T_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_T);
    connect(m_menuBar->V_T_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_O);
    connect(m_menuBar->V_T_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_T_U);
    connect(m_menuBar->V_W_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_W_N);
    connect(m_menuBar->V_W_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_W_W);
    connect(m_menuBar->V_W_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_W_C);
    connect(m_menuBar->V_W_H,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_W_H);
    connect(m_menuBar->V_L_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_L_M);
    connect(m_menuBar->V_L_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_L_T);
    connect(m_menuBar->V_L_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_L_C);
    connect(m_menuBar->V_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_I);
    connect(m_menuBar->V_C_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_C_D);
    connect(m_menuBar->V_C_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_C_U);
    connect(m_menuBar->V_C_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_C_S);
    connect(m_menuBar->V_C_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_C_E);
    connect(m_menuBar->V_C_V,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_C_V);
    connect(m_menuBar->V_O_H,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_H);
    connect(m_menuBar->V_O_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_A);
    connect(m_menuBar->V_O_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_C);
    connect(m_menuBar->V_O_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_E);
    connect(m_menuBar->V_O_S_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_S_D);
    connect(m_menuBar->V_O_S_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_S_P);
    connect(m_menuBar->V_O_S_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_S_C);
    connect(m_menuBar->V_O_S_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_S_B);
    connect(m_menuBar->V_O_S_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_S_T);
    connect(m_menuBar->V_O_S_X,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_V_O_S_X);
    connect(m_menuBar->I_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_F);
    connect(m_menuBar->I_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_T);
    connect(m_menuBar->I_V,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_V);
    connect(m_menuBar->I_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_A);
    connect(m_menuBar->I_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_B);
    connect(m_menuBar->I_N_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_N_W);
    connect(m_menuBar->I_N_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_N_M);
    connect(m_menuBar->I_N_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_N_U);
    connect(m_menuBar->I_D_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_D_D);
    connect(m_menuBar->I_D_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_D_T);
    connect(m_menuBar->I_D_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_D_A);
    connect(m_menuBar->I_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_I_O);
    connect(m_menuBar->O_L_p,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_p);
    connect(m_menuBar->O_L_A_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_A_C);
    connect(m_menuBar->O_L_A_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_A_S);
    connect(m_menuBar->O_L_A_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_A_A);
    connect(m_menuBar->O_L_B_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_B_B);
    connect(m_menuBar->O_L_B_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_B_T);
    connect(m_menuBar->O_L_B_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_B_S);
    connect(m_menuBar->O_L_B_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_B_A);
    connect(m_menuBar->O_L_B_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_B_F);
    connect(m_menuBar->O_L_C_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_C_C);
    connect(m_menuBar->O_L_C_pl,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_C_pl);
    connect(m_menuBar->O_L_C_p,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_C_p);
    connect(m_menuBar->O_L_C_s,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_C_s);
    connect(m_menuBar->O_L_C_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_C_M);
    connect(m_menuBar->O_L_C_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_C_O);
    connect(m_menuBar->O_L_C_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_C_S);
    connect(m_menuBar->O_L_D_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_D_D);
    connect(m_menuBar->O_L_D_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_D_I);
    connect(m_menuBar->O_L_E_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_E_E);
    connect(m_menuBar->O_L_F_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_F_F);
    connect(m_menuBar->O_L_F_7,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_F_7);
    connect(m_menuBar->O_L_G_G,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_G_G);
    connect(m_menuBar->O_L_H_H,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_H_H);
    connect(m_menuBar->O_L_H_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_H_T);
    connect(m_menuBar->O_L_I_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_I_I);
    connect(m_menuBar->O_L_I_H,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_I_H);
    connect(m_menuBar->O_L_J_J,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_J_J);
    connect(m_menuBar->O_L_J_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_J_S);
    connect(m_menuBar->O_L_J_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_J_O);
    connect(m_menuBar->O_L_L_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_L_T);
    connect(m_menuBar->O_L_L_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_L_L);
    connect(m_menuBar->O_L_M_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_M_F);
    connect(m_menuBar->O_L_M_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_M_D);
    connect(m_menuBar->O_L_M_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_M_M);
    connect(m_menuBar->O_L_M_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_M_L);
    connect(m_menuBar->O_L_N_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_N_N);
    connect(m_menuBar->O_L_O_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_O_O);
    connect(m_menuBar->O_L_P_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_P);
    connect(m_menuBar->O_L_P_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_E);
    connect(m_menuBar->O_L_P_H,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_H);
    connect(m_menuBar->O_L_P_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_O);
    connect(m_menuBar->O_L_P_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_S);
    connect(m_menuBar->O_L_P_V,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_V);
    connect(m_menuBar->O_L_P_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_R);
    connect(m_menuBar->O_L_P_2,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_2);
    connect(m_menuBar->O_L_P_3,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_3);
    connect(m_menuBar->O_L_P_X,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_P_X);
    connect(m_menuBar->O_L_Q_Q,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_Q_Q);
    connect(m_menuBar->O_L_Q_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_Q_S);
    connect(m_menuBar->O_L_Q_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_Q_U);
    connect(m_menuBar->O_L_R_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_R_R);
    connect(m_menuBar->O_L_S_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_S_S);
    connect(m_menuBar->O_L_S_Q,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_S_Q);
    connect(m_menuBar->O_L_S_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_S_R);
    connect(m_menuBar->O_L_T_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_T_T);
    connect(m_menuBar->O_L_T_H,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_T_H);
    connect(m_menuBar->O_L_T_X,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_T_X);
    connect(m_menuBar->O_L_V_V,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_V_V);
    connect(m_menuBar->O_L_V_H,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_V_H);
    connect(m_menuBar->O_L_X_X,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_X_X);
    connect(m_menuBar->O_L_Y_Y,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_L_Y_Y);
    connect(m_menuBar->O_N_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_N_U);
    connect(m_menuBar->O_N_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_N_C);
    connect(m_menuBar->O_N_E,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_N_E);
    connect(m_menuBar->O_N_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_N_T);
    connect(m_menuBar->O_N_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_N_M);
    connect(m_menuBar->O_N_X,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_N_X);
    connect(m_menuBar->O_C_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_C_U);
    connect(m_menuBar->O_C_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_C_L);
    connect(m_menuBar->O_C_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_C_T);
    connect(m_menuBar->O_C_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_C_S);
    connect(m_menuBar->O_C_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_C_I);
    connect(m_menuBar->O_C_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_C_R);
    connect(m_menuBar->O_I_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_I_T);
    connect(m_menuBar->O_I_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_I_B);
    connect(m_menuBar->O_I_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_I_I);
    connect(m_menuBar->O_R_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_R_L);
    connect(m_menuBar->O_R_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_R_S);
    connect(m_menuBar->O_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_S);
    connect(m_menuBar->O_h,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_h);
    connect(m_menuBar->O_A_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_A_U);
    connect(m_menuBar->O_A_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_O_A_L);
    connect(m_menuBar->T_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_P);
    connect(m_menuBar->T_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_R);
    connect(m_menuBar->T_A_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_C);
    connect(m_menuBar->T_A_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_F);
    connect(m_menuBar->T_A_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_R);
    connect(m_menuBar->T_A_W_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_W_N);
    connect(m_menuBar->T_A_W_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_W_O);
    connect(m_menuBar->T_A_W_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_W_D);
    connect(m_menuBar->T_A_S_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_S_D);
    connect(m_menuBar->T_A_S_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_S_A);
    connect(m_menuBar->T_A_S_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_S_O);
    connect(m_menuBar->T_A_S_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_S_L);
    connect(m_menuBar->T_A_T_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_T_A);
    connect(m_menuBar->T_A_T_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_T_D);
    connect(m_menuBar->T_A_T_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_A_T_L);
    connect(m_menuBar->T_h_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_h_A);
    connect(m_menuBar->T_h_S_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_h_S_A);
    connect(m_menuBar->T_h_S_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_h_S_M);
    connect(m_menuBar->T_h_S_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_h_S_O);
    connect(m_menuBar->T_h_S_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_h_S_C);
    connect(m_menuBar->T_B_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_B_N);
    connect(m_menuBar->T_B_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_B_S);
    connect(m_menuBar->T_B_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_B_B);
    connect(m_menuBar->T_B_I_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_B_I_B);
    connect(m_menuBar->T_B_I_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_B_I_N);
    connect(m_menuBar->T_B_I_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_B_I_S);
    connect(m_menuBar->T_B_D_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_B_D_B);
    connect(m_menuBar->T_C_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_C_T);
    connect(m_menuBar->T_C_P_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_C_P_B);
    connect(m_menuBar->T_C_P_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_C_P_A);
    connect(m_menuBar->T_C_S_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_C_S_D);
    connect(m_menuBar->T_C_S_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_C_S_N);
    connect(m_menuBar->T_C_S_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_C_S_A);
    connect(m_menuBar->T_C_S_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_C_S_W);
    connect(m_menuBar->T_E_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_E_N);
    connect(m_menuBar->T_E_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_E_L);
    connect(m_menuBar->T_E_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_E_B);
    connect(m_menuBar->T_V_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_S);
    connect(m_menuBar->T_V_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_M);
    connect(m_menuBar->T_V_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_A);
    connect(m_menuBar->T_V_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_P);
    connect(m_menuBar->T_V_V_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_V_D);
    connect(m_menuBar->T_V_V_R,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_V_R);
    connect(m_menuBar->T_V_V_U,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_V_U);
    connect(m_menuBar->T_V_V_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_V_W);
    connect(m_menuBar->T_V_R_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_R_C);
    connect(m_menuBar->T_V_R_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_R_A);
    connect(m_menuBar->T_V_C_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_C_O);
    connect(m_menuBar->T_V_C_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_C_N);
    connect(m_menuBar->T_V_C_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_V_C_W);
    connect(m_menuBar->T_S_R_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_S_R_N);
    connect(m_menuBar->T_S_R_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_S_R_S);
    connect(m_menuBar->T_S_R_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_S_R_P);
    connect(m_menuBar->T_S_R_pl,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_S_R_pl);
    connect(m_menuBar->T_S_C,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_S_C);
    connect(m_menuBar->T_S_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_S_O);
    connect(m_menuBar->T_S_W,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_S_W);
    connect(m_menuBar->T_S_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_S_S);
    connect(m_menuBar->T_S_G,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_S_G);
    connect(m_menuBar->T_W_I_P,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_I_P);
    connect(m_menuBar->T_W_I_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_I_S);
    connect(m_menuBar->T_W_I_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_I_I);
    connect(m_menuBar->T_W_I_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_I_D);
    connect(m_menuBar->T_W_S_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_S_N);
    connect(m_menuBar->T_W_S_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_S_T);
    connect(m_menuBar->T_W_S_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_S_B);
    connect(m_menuBar->T_W_S_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_S_M);
    connect(m_menuBar->T_W_E_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_E_N);
    connect(m_menuBar->T_W_E_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_E_T);
    connect(m_menuBar->T_W_E_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_E_B);
    connect(m_menuBar->T_W_E_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_W_E_M);
    connect(m_menuBar->T_M_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_M_B);
    connect(m_menuBar->T_M_P_O,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_M_P_O);
    connect(m_menuBar->T_M_P_T,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_M_P_T);
    connect(m_menuBar->T_M_P_M,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_M_P_M);
    connect(m_menuBar->T_M_Q_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_M_Q_D);
    connect(m_menuBar->T_M_Q_N,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_M_Q_N);
    connect(m_menuBar->T_M_Q_A,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_M_Q_A);
    connect(m_menuBar->T_M_Q_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_T_M_Q_L);
    connect(m_menuBar->W_F,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_W_F);
    connect(m_menuBar->W_L,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_W_L);
    connect(m_menuBar->W_B,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_W_B);
    connect(m_menuBar->W_D,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_W_D);
    connect(m_menuBar->W_I,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_W_I);
    connect(m_menuBar->W_S,
            &TpGeneralAction::triggered,
            this,
            &TpMainWindow::onAction_W_S);

    connect(m_widget->tabs(),
            &TpTabSplitter::tabChanged,
            this,
            &TpMainWindow::onTabChanged);
    connect(m_widget->tabs(),
            &TpTabSplitter::tabCloseRequested,
            this,
            &TpMainWindow::onTabCloseRequested);
    connect(m_widget->tabs(),
            &TpTabSplitter::tabsListChanged,
            this,
            &TpMainWindow::onTabsListChanged);

    connect(this,
            &TpMainWindow::wrapVisualFlagChanged,
            this,
            &TpMainWindow::onWrapVisualFlagChanged);

    connect(m_fileDock,
            &TpFileDock::visibilityChanged,
            this,
            &TpMainWindow::onFileDockVisibilityChanged);
    connect(m_fileDock,
            &TpFileDock::fileDoubleClicked,
            this,
            &TpMainWindow::onFileDockDoubleClicked);
    connect(m_documentDock,
            &TpDocumentDock::visibilityChanged,
            this,
            &TpMainWindow::onDocumentDockVisibilityChanged);
    connect(m_documentDock,
            &TpDocumentDock::fileDoubleClicked,
            this,
            &TpMainWindow::onDocumentDockDoubleClicked);
    connect(m_bookmarkDock,
            &TpBookmarkDock::visibilityChanged,
            this,
            &TpMainWindow::onBookmarkDockVisibilityChanged);
    connect(m_findDock,
            &TpFindDock::visibilityChanged,
            this,
            &TpMainWindow::onFindDockVisibilityChanged);
    connect(m_findInFilesDock,
            &TpFindInFilesDock::visibilityChanged,
            this,
            &TpMainWindow::onFindInFilesDockVisibilityChanged);
    connect(m_findInFilesDock,
            &TpFindInFilesDock::resultClicked,
            this,
            &TpMainWindow::onFindInFilesDockDoubleClicked);

    connect(m_findToolBar,
            &TpFindToolBar::textChanged,
            this,
            &TpMainWindow::onFindToolBarTextChanged);

    connect(m_statusBar->m_spinBoxTabWidth,
            qOverload<int>(&QSpinBox::valueChanged),
            this,
            &TpMainWindow::onStatusBarSpinBoxTabWidthChanged);
#if QT_VERSION_MAJOR >= 6
    connect(m_statusBar->m_comboBoxLang,
            &TpGeneralComboBox::currentIndexChanged,
            this,
            &TpMainWindow::onStatusBarComboBoxLangIndexChanged);
    connect(m_statusBar->m_comboBoxNewLine,
            &TpGeneralComboBox::currentIndexChanged,
            this,
            &TpMainWindow::onStatusBarComboBoxNewLineIndexChanged);
#else
    connect(m_statusBar->m_comboBoxLang,
            SIGNAL(currentIndexChanged(int)),
            this,
            SLOT(onStatusBarComboBoxLangIndexChanged(int)));
    connect(m_statusBar->m_comboBoxNewLine,
            SIGNAL(currentIndexChanged(int)),
            this,
            SLOT(onStatusBarComboBoxNewLineIndexChanged(int)));
#endif
}

TP_END_NAMESPACE
