#include <Widgets/TpSettingsPage>
#include <TpColorScheme>

TP_NAMESPACE

void writeColorSchemeToSettings(TpColorScheme *scheme)
{
    DEF_SETTINGS;

    SET_SETTINGS("Editor/Color/Universal", scheme->Default);
    SET_SETTINGS("Editor/Color/Comment", scheme->Comment);
    SET_SETTINGS("Editor/Color/CommentLine", scheme->CommentLine);
    SET_SETTINGS("Editor/Color/CommentDoc", scheme->CommentDoc);
    SET_SETTINGS("Editor/Color/Number", scheme->Number);
    SET_SETTINGS("Editor/Color/Keyword", scheme->Keyword);
    SET_SETTINGS("Editor/Color/DoubleQuotedString", scheme->DoubleQuotedString);
    SET_SETTINGS("Editor/Color/SingleQuotedString", scheme->SingleQuotedString);
    SET_SETTINGS("Editor/Color/UUID", scheme->UUID);
    SET_SETTINGS("Editor/Color/PreProcessor", scheme->PreProcessor);
    SET_SETTINGS("Editor/Color/Operator", scheme->Operator);
    SET_SETTINGS("Editor/Color/Identifier", scheme->Identifier);
    SET_SETTINGS("Editor/Color/UnclosedString", scheme->UnclosedString);
    SET_SETTINGS("Editor/Color/VerbatimString", scheme->VerbatimString);
    SET_SETTINGS("Editor/Color/Regex", scheme->Regex);
    SET_SETTINGS("Editor/Color/CommentLineDoc", scheme->CommentLineDoc);
    SET_SETTINGS("Editor/Color/KeywordSet2", scheme->KeywordSet2);
    SET_SETTINGS("Editor/Color/CommentDocKeyword", scheme->CommentDocKeyword);
    SET_SETTINGS("Editor/Color/CommentDocKeywordError", scheme->CommentDocKeywordError);
    SET_SETTINGS("Editor/Color/GlobalClass", scheme->GlobalClass);
    SET_SETTINGS("Editor/Color/RawString", scheme->RawString);
    SET_SETTINGS("Editor/Color/TripleQuotedVerbatimString", scheme->TripleQuotedVerbatimString);
    SET_SETTINGS("Editor/Color/HashQuotedString", scheme->HashQuotedString);
    SET_SETTINGS("Editor/Color/PreProcessorComment", scheme->PreProcessorComment);
    SET_SETTINGS("Editor/Color/PreProcessorCommentLineDoc", scheme->PreProcessorCommentLineDoc);
    SET_SETTINGS("Editor/Color/UserLiteral", scheme->UserLiteral);
    SET_SETTINGS("Editor/Color/TaskMarker", scheme->TaskMarker);
    SET_SETTINGS("Editor/Color/EscapeSequence", scheme->EscapeSequence);
    SET_SETTINGS("Editor/Color/InactiveDefault", scheme->InactiveDefault);
    SET_SETTINGS("Editor/Color/InactiveComment", scheme->InactiveComment);
    SET_SETTINGS("Editor/Color/InactiveCommentLine", scheme->InactiveCommentLine);
    SET_SETTINGS("Editor/Color/InactiveCommentDoc", scheme->InactiveCommentDoc);
    SET_SETTINGS("Editor/Color/InactiveNumber", scheme->InactiveNumber);
    SET_SETTINGS("Editor/Color/InactiveKeyword", scheme->InactiveKeyword);
    SET_SETTINGS("Editor/Color/InactiveDoubleQuotedString", scheme->InactiveDoubleQuotedString);
    SET_SETTINGS("Editor/Color/InactiveSingleQuotedString", scheme->InactiveSingleQuotedString);
    SET_SETTINGS("Editor/Color/InactiveUUID", scheme->InactiveUUID);
    SET_SETTINGS("Editor/Color/InactivePreProcessor", scheme->InactivePreProcessor);
    SET_SETTINGS("Editor/Color/InactiveOperator", scheme->InactiveOperator);
    SET_SETTINGS("Editor/Color/InactiveIdentifier", scheme->InactiveIdentifier);
    SET_SETTINGS("Editor/Color/InactiveUnclosedString", scheme->InactiveUnclosedString);
    SET_SETTINGS("Editor/Color/InactiveVerbatimString", scheme->InactiveVerbatimString);
    SET_SETTINGS("Editor/Color/InactiveRegex", scheme->InactiveRegex);
    SET_SETTINGS("Editor/Color/InactiveCommentLineDoc", scheme->InactiveCommentLineDoc);
    SET_SETTINGS("Editor/Color/InactiveKeywordSet2", scheme->InactiveKeywordSet2);
    SET_SETTINGS("Editor/Color/InactiveCommentDocKeyword", scheme->InactiveCommentDocKeyword);
    SET_SETTINGS("Editor/Color/InactiveCommentDocKeywordError", scheme->InactiveCommentDocKeywordError);
    SET_SETTINGS("Editor/Color/InactiveGlobalClass", scheme->InactiveGlobalClass);
    SET_SETTINGS("Editor/Color/InactiveRawString", scheme->InactiveRawString);
    SET_SETTINGS("Editor/Color/InactiveTripleQuotedVerbatimString", scheme->InactiveTripleQuotedVerbatimString);
    SET_SETTINGS("Editor/Color/InactiveHashQuotedString", scheme->InactiveHashQuotedString);
    SET_SETTINGS("Editor/Color/InactivePreProcessorComment", scheme->InactivePreProcessorComment);
    SET_SETTINGS("Editor/Color/InactivePreProcessorCommentLineDoc", scheme->InactivePreProcessorCommentLineDoc);
    SET_SETTINGS("Editor/Color/InactiveUserLiteral", scheme->InactiveUserLiteral);
    SET_SETTINGS("Editor/Color/InactiveTaskMarker", scheme->InactiveTaskMarker);
    SET_SETTINGS("Editor/Color/InactiveEscapeSequence", scheme->InactiveEscapeSequence);
    SET_SETTINGS("Editor/Color/Error", scheme->Error);
    SET_SETTINGS("Editor/Color/Type", scheme->Type);
    SET_SETTINGS("Editor/Color/PrimitiveType", scheme->PrimitiveType);
    SET_SETTINGS("Editor/Color/Warning", scheme->Warning);
    SET_SETTINGS("Editor/Color/WeakWarning", scheme->WeakWarning);
    SET_SETTINGS("Editor/BgColor/Universal", scheme->BgDefault);
    SET_SETTINGS("Editor/BgColor/Comment", scheme->BgComment);
    SET_SETTINGS("Editor/BgColor/CommentLine", scheme->BgCommentLine);
    SET_SETTINGS("Editor/BgColor/CommentDoc", scheme->BgCommentDoc);
    SET_SETTINGS("Editor/BgColor/Number", scheme->BgNumber);
    SET_SETTINGS("Editor/BgColor/Keyword", scheme->BgKeyword);
    SET_SETTINGS("Editor/BgColor/DoubleQuotedString", scheme->BgDoubleQuotedString);
    SET_SETTINGS("Editor/BgColor/SingleQuotedString", scheme->BgSingleQuotedString);
    SET_SETTINGS("Editor/BgColor/UUID", scheme->BgUUID);
    SET_SETTINGS("Editor/BgColor/PreProcessor", scheme->BgPreProcessor);
    SET_SETTINGS("Editor/BgColor/Operator", scheme->BgOperator);
    SET_SETTINGS("Editor/BgColor/Identifier", scheme->BgIdentifier);
    SET_SETTINGS("Editor/BgColor/UnclosedString", scheme->BgUnclosedString);
    SET_SETTINGS("Editor/BgColor/VerbatimString", scheme->BgVerbatimString);
    SET_SETTINGS("Editor/BgColor/Regex", scheme->BgRegex);
    SET_SETTINGS("Editor/BgColor/CommentLineDoc", scheme->BgCommentLineDoc);
    SET_SETTINGS("Editor/BgColor/KeywordSet2", scheme->BgKeywordSet2);
    SET_SETTINGS("Editor/BgColor/CommentDocKeyword", scheme->BgCommentDocKeyword);
    SET_SETTINGS("Editor/BgColor/CommentDocKeywordError", scheme->BgCommentDocKeywordError);
    SET_SETTINGS("Editor/BgColor/GlobalClass", scheme->BgGlobalClass);
    SET_SETTINGS("Editor/BgColor/RawString", scheme->BgRawString);
    SET_SETTINGS("Editor/BgColor/TripleQuotedVerbatimString", scheme->BgTripleQuotedVerbatimString);
    SET_SETTINGS("Editor/BgColor/HashQuotedString", scheme->BgHashQuotedString);
    SET_SETTINGS("Editor/BgColor/PreProcessorComment", scheme->BgPreProcessorComment);
    SET_SETTINGS("Editor/BgColor/PreProcessorCommentLineDoc", scheme->BgPreProcessorCommentLineDoc);
    SET_SETTINGS("Editor/BgColor/UserLiteral", scheme->BgUserLiteral);
    SET_SETTINGS("Editor/BgColor/TaskMarker", scheme->BgTaskMarker);
    SET_SETTINGS("Editor/BgColor/EscapeSequence", scheme->BgEscapeSequence);
    SET_SETTINGS("Editor/BgColor/InactiveDefault", scheme->BgInactiveDefault);
    SET_SETTINGS("Editor/BgColor/InactiveComment", scheme->BgInactiveComment);
    SET_SETTINGS("Editor/BgColor/InactiveCommentLine", scheme->BgInactiveCommentLine);
    SET_SETTINGS("Editor/BgColor/InactiveCommentDoc", scheme->BgInactiveCommentDoc);
    SET_SETTINGS("Editor/BgColor/InactiveNumber", scheme->BgInactiveNumber);
    SET_SETTINGS("Editor/BgColor/InactiveKeyword", scheme->BgInactiveKeyword);
    SET_SETTINGS("Editor/BgColor/InactiveDoubleQuotedString", scheme->BgInactiveDoubleQuotedString);
    SET_SETTINGS("Editor/BgColor/InactiveSingleQuotedString", scheme->BgInactiveSingleQuotedString);
    SET_SETTINGS("Editor/BgColor/InactiveUUID", scheme->BgInactiveUUID);
    SET_SETTINGS("Editor/BgColor/InactivePreProcessor", scheme->BgInactivePreProcessor);
    SET_SETTINGS("Editor/BgColor/InactiveOperator", scheme->BgInactiveOperator);
    SET_SETTINGS("Editor/BgColor/InactiveIdentifier", scheme->BgInactiveIdentifier);
    SET_SETTINGS("Editor/BgColor/InactiveUnclosedString", scheme->BgInactiveUnclosedString);
    SET_SETTINGS("Editor/BgColor/InactiveVerbatimString", scheme->BgInactiveVerbatimString);
    SET_SETTINGS("Editor/BgColor/InactiveRegex", scheme->BgInactiveRegex);
    SET_SETTINGS("Editor/BgColor/InactiveCommentLineDoc", scheme->BgInactiveCommentLineDoc);
    SET_SETTINGS("Editor/BgColor/InactiveKeywordSet2", scheme->BgInactiveKeywordSet2);
    SET_SETTINGS("Editor/BgColor/InactiveCommentDocKeyword", scheme->BgInactiveCommentDocKeyword);
    SET_SETTINGS("Editor/BgColor/InactiveCommentDocKeywordError", scheme->BgInactiveCommentDocKeywordError);
    SET_SETTINGS("Editor/BgColor/InactiveGlobalClass", scheme->BgInactiveGlobalClass);
    SET_SETTINGS("Editor/BgColor/InactiveRawString", scheme->BgInactiveRawString);
    SET_SETTINGS("Editor/BgColor/InactiveTripleQuotedVerbatimString", scheme->BgInactiveTripleQuotedVerbatimString);
    SET_SETTINGS("Editor/BgColor/InactiveHashQuotedString", scheme->BgInactiveHashQuotedString);
    SET_SETTINGS("Editor/BgColor/InactivePreProcessorComment", scheme->BgInactivePreProcessorComment);
    SET_SETTINGS("Editor/BgColor/InactivePreProcessorCommentLineDoc", scheme->BgInactivePreProcessorCommentLineDoc);
    SET_SETTINGS("Editor/BgColor/InactiveUserLiteral", scheme->BgInactiveUserLiteral);
    SET_SETTINGS("Editor/BgColor/InactiveTaskMarker", scheme->BgInactiveTaskMarker);
    SET_SETTINGS("Editor/BgColor/InactiveEscapeSequence", scheme->BgInactiveEscapeSequence);
    SET_SETTINGS("Editor/BgColor/Error", scheme->BgError);
    SET_SETTINGS("Editor/BgColor/Type", scheme->BgType);
    SET_SETTINGS("Editor/BgColor/PrimitiveType", scheme->BgPrimitiveType);
    SET_SETTINGS("Editor/BgColor/Warning", scheme->BgWarning);
    SET_SETTINGS("Editor/BgColor/WeakWarning", scheme->BgWeakWarning);
}

void readFromSettingsToDefaultColorScheme()
{
    DEF_SETTINGS;

    defaultColorScheme->Default = GET_SETTINGS("Editor/Color/Universal", QColor);
    defaultColorScheme->Comment = GET_SETTINGS("Editor/Color/Comment", QColor);
    defaultColorScheme->CommentLine = GET_SETTINGS("Editor/Color/CommentLine", QColor);
    defaultColorScheme->CommentDoc = GET_SETTINGS("Editor/Color/CommentDoc", QColor);
    defaultColorScheme->Number = GET_SETTINGS("Editor/Color/Number", QColor);
    defaultColorScheme->Keyword = GET_SETTINGS("Editor/Color/Keyword", QColor);
    defaultColorScheme->DoubleQuotedString = GET_SETTINGS("Editor/Color/DoubleQuotedString", QColor);
    defaultColorScheme->SingleQuotedString = GET_SETTINGS("Editor/Color/SingleQuotedString", QColor);
    defaultColorScheme->UUID = GET_SETTINGS("Editor/Color/UUID", QColor);
    defaultColorScheme->PreProcessor = GET_SETTINGS("Editor/Color/PreProcessor", QColor);
    defaultColorScheme->Operator = GET_SETTINGS("Editor/Color/Operator", QColor);
    defaultColorScheme->Identifier = GET_SETTINGS("Editor/Color/Identifier", QColor);
    defaultColorScheme->UnclosedString = GET_SETTINGS("Editor/Color/UnclosedString", QColor);
    defaultColorScheme->VerbatimString = GET_SETTINGS("Editor/Color/VerbatimString", QColor);
    defaultColorScheme->Regex = GET_SETTINGS("Editor/Color/Regex", QColor);
    defaultColorScheme->CommentLineDoc = GET_SETTINGS("Editor/Color/CommentLineDoc", QColor);
    defaultColorScheme->KeywordSet2 = GET_SETTINGS("Editor/Color/KeywordSet2", QColor);
    defaultColorScheme->CommentDocKeyword = GET_SETTINGS("Editor/Color/CommentDocKeyword", QColor);
    defaultColorScheme->CommentDocKeywordError = GET_SETTINGS("Editor/Color/CommentDocKeywordError", QColor);
    defaultColorScheme->GlobalClass = GET_SETTINGS("Editor/Color/GlobalClass", QColor);
    defaultColorScheme->RawString = GET_SETTINGS("Editor/Color/RawString", QColor);
    defaultColorScheme->TripleQuotedVerbatimString = GET_SETTINGS("Editor/Color/TripleQuotedVerbatimString", QColor);
    defaultColorScheme->HashQuotedString = GET_SETTINGS("Editor/Color/HashQuotedString", QColor);
    defaultColorScheme->PreProcessorComment = GET_SETTINGS("Editor/Color/PreProcessorComment", QColor);
    defaultColorScheme->PreProcessorCommentLineDoc = GET_SETTINGS("Editor/Color/PreProcessorCommentLineDoc", QColor);
    defaultColorScheme->UserLiteral = GET_SETTINGS("Editor/Color/UserLiteral", QColor);
    defaultColorScheme->TaskMarker = GET_SETTINGS("Editor/Color/TaskMarker", QColor);
    defaultColorScheme->EscapeSequence = GET_SETTINGS("Editor/Color/EscapeSequence", QColor);
    defaultColorScheme->InactiveDefault = GET_SETTINGS("Editor/Color/InactiveDefault", QColor);
    defaultColorScheme->InactiveComment = GET_SETTINGS("Editor/Color/InactiveComment", QColor);
    defaultColorScheme->InactiveCommentLine = GET_SETTINGS("Editor/Color/InactiveCommentLine", QColor);
    defaultColorScheme->InactiveCommentDoc = GET_SETTINGS("Editor/Color/InactiveCommentDoc", QColor);
    defaultColorScheme->InactiveNumber = GET_SETTINGS("Editor/Color/InactiveNumber", QColor);
    defaultColorScheme->InactiveKeyword = GET_SETTINGS("Editor/Color/InactiveKeyword", QColor);
    defaultColorScheme->InactiveDoubleQuotedString = GET_SETTINGS("Editor/Color/InactiveDoubleQuotedString", QColor);
    defaultColorScheme->InactiveSingleQuotedString = GET_SETTINGS("Editor/Color/InactiveSingleQuotedString", QColor);
    defaultColorScheme->InactiveUUID = GET_SETTINGS("Editor/Color/InactiveUUID", QColor);
    defaultColorScheme->InactivePreProcessor = GET_SETTINGS("Editor/Color/InactivePreProcessor", QColor);
    defaultColorScheme->InactiveOperator = GET_SETTINGS("Editor/Color/InactiveOperator", QColor);
    defaultColorScheme->InactiveIdentifier = GET_SETTINGS("Editor/Color/InactiveIdentifier", QColor);
    defaultColorScheme->InactiveUnclosedString = GET_SETTINGS("Editor/Color/InactiveUnclosedString", QColor);
    defaultColorScheme->InactiveVerbatimString = GET_SETTINGS("Editor/Color/InactiveVerbatimString", QColor);
    defaultColorScheme->InactiveRegex = GET_SETTINGS("Editor/Color/InactiveRegex", QColor);
    defaultColorScheme->InactiveCommentLineDoc = GET_SETTINGS("Editor/Color/InactiveCommentLineDoc", QColor);
    defaultColorScheme->InactiveKeywordSet2 = GET_SETTINGS("Editor/Color/InactiveKeywordSet2", QColor);
    defaultColorScheme->InactiveCommentDocKeyword = GET_SETTINGS("Editor/Color/InactiveCommentDocKeyword", QColor);
    defaultColorScheme->InactiveCommentDocKeywordError = GET_SETTINGS("Editor/Color/InactiveCommentDocKeywordError", QColor);
    defaultColorScheme->InactiveGlobalClass = GET_SETTINGS("Editor/Color/InactiveGlobalClass", QColor);
    defaultColorScheme->InactiveRawString = GET_SETTINGS("Editor/Color/InactiveRawString", QColor);
    defaultColorScheme->InactiveTripleQuotedVerbatimString = GET_SETTINGS("Editor/Color/InactiveTripleQuotedVerbatimString", QColor);
    defaultColorScheme->InactiveHashQuotedString = GET_SETTINGS("Editor/Color/InactiveHashQuotedString", QColor);
    defaultColorScheme->InactivePreProcessorComment = GET_SETTINGS("Editor/Color/InactivePreProcessorComment", QColor);
    defaultColorScheme->InactivePreProcessorCommentLineDoc = GET_SETTINGS("Editor/Color/InactivePreProcessorCommentLineDoc", QColor);
    defaultColorScheme->InactiveUserLiteral = GET_SETTINGS("Editor/Color/InactiveUserLiteral", QColor);
    defaultColorScheme->InactiveTaskMarker = GET_SETTINGS("Editor/Color/InactiveTaskMarker", QColor);
    defaultColorScheme->InactiveEscapeSequence = GET_SETTINGS("Editor/Color/InactiveEscapeSequence", QColor);
    defaultColorScheme->Error = GET_SETTINGS("Editor/Color/Error", QColor);
    defaultColorScheme->Type = GET_SETTINGS("Editor/Color/Type", QColor);
    defaultColorScheme->PrimitiveType = GET_SETTINGS("Editor/Color/PrimitiveType", QColor);
    defaultColorScheme->Warning = GET_SETTINGS("Editor/Color/Warning", QColor);
    defaultColorScheme->WeakWarning = GET_SETTINGS("Editor/Color/WeakWarning", QColor);
    defaultColorScheme->BgDefault = GET_SETTINGS("Editor/BgColor/Universal", QColor);
    defaultColorScheme->BgComment = GET_SETTINGS("Editor/BgColor/Comment", QColor);
    defaultColorScheme->BgCommentLine = GET_SETTINGS("Editor/BgColor/CommentLine", QColor);
    defaultColorScheme->BgCommentDoc = GET_SETTINGS("Editor/BgColor/CommentDoc", QColor);
    defaultColorScheme->BgNumber = GET_SETTINGS("Editor/BgColor/Number", QColor);
    defaultColorScheme->BgKeyword = GET_SETTINGS("Editor/BgColor/Keyword", QColor);
    defaultColorScheme->BgDoubleQuotedString = GET_SETTINGS("Editor/BgColor/DoubleQuotedString", QColor);
    defaultColorScheme->BgSingleQuotedString = GET_SETTINGS("Editor/BgColor/SingleQuotedString", QColor);
    defaultColorScheme->BgUUID = GET_SETTINGS("Editor/BgColor/UUID", QColor);
    defaultColorScheme->BgPreProcessor = GET_SETTINGS("Editor/BgColor/PreProcessor", QColor);
    defaultColorScheme->BgOperator = GET_SETTINGS("Editor/BgColor/Operator", QColor);
    defaultColorScheme->BgIdentifier = GET_SETTINGS("Editor/BgColor/Identifier", QColor);
    defaultColorScheme->BgUnclosedString = GET_SETTINGS("Editor/BgColor/UnclosedString", QColor);
    defaultColorScheme->BgVerbatimString = GET_SETTINGS("Editor/BgColor/VerbatimString", QColor);
    defaultColorScheme->BgRegex = GET_SETTINGS("Editor/BgColor/Regex", QColor);
    defaultColorScheme->BgCommentLineDoc = GET_SETTINGS("Editor/BgColor/CommentLineDoc", QColor);
    defaultColorScheme->BgKeywordSet2 = GET_SETTINGS("Editor/BgColor/KeywordSet2", QColor);
    defaultColorScheme->BgCommentDocKeyword = GET_SETTINGS("Editor/BgColor/CommentDocKeyword", QColor);
    defaultColorScheme->BgCommentDocKeywordError = GET_SETTINGS("Editor/BgColor/CommentDocKeywordError", QColor);
    defaultColorScheme->BgGlobalClass = GET_SETTINGS("Editor/BgColor/GlobalClass", QColor);
    defaultColorScheme->BgRawString = GET_SETTINGS("Editor/BgColor/RawString", QColor);
    defaultColorScheme->BgTripleQuotedVerbatimString = GET_SETTINGS("Editor/BgColor/TripleQuotedVerbatimString", QColor);
    defaultColorScheme->BgHashQuotedString = GET_SETTINGS("Editor/BgColor/HashQuotedString", QColor);
    defaultColorScheme->BgPreProcessorComment = GET_SETTINGS("Editor/BgColor/PreProcessorComment", QColor);
    defaultColorScheme->BgPreProcessorCommentLineDoc = GET_SETTINGS("Editor/BgColor/PreProcessorCommentLineDoc", QColor);
    defaultColorScheme->BgUserLiteral = GET_SETTINGS("Editor/BgColor/UserLiteral", QColor);
    defaultColorScheme->BgTaskMarker = GET_SETTINGS("Editor/BgColor/TaskMarker", QColor);
    defaultColorScheme->BgEscapeSequence = GET_SETTINGS("Editor/BgColor/EscapeSequence", QColor);
    defaultColorScheme->BgInactiveDefault = GET_SETTINGS("Editor/BgColor/InactiveDefault", QColor);
    defaultColorScheme->BgInactiveComment = GET_SETTINGS("Editor/BgColor/InactiveComment", QColor);
    defaultColorScheme->BgInactiveCommentLine = GET_SETTINGS("Editor/BgColor/InactiveCommentLine", QColor);
    defaultColorScheme->BgInactiveCommentDoc = GET_SETTINGS("Editor/BgColor/InactiveCommentDoc", QColor);
    defaultColorScheme->BgInactiveNumber = GET_SETTINGS("Editor/BgColor/InactiveNumber", QColor);
    defaultColorScheme->BgInactiveKeyword = GET_SETTINGS("Editor/BgColor/InactiveKeyword", QColor);
    defaultColorScheme->BgInactiveDoubleQuotedString = GET_SETTINGS("Editor/BgColor/InactiveDoubleQuotedString", QColor);
    defaultColorScheme->BgInactiveSingleQuotedString = GET_SETTINGS("Editor/BgColor/InactiveSingleQuotedString", QColor);
    defaultColorScheme->BgInactiveUUID = GET_SETTINGS("Editor/BgColor/InactiveUUID", QColor);
    defaultColorScheme->BgInactivePreProcessor = GET_SETTINGS("Editor/BgColor/InactivePreProcessor", QColor);
    defaultColorScheme->BgInactiveOperator = GET_SETTINGS("Editor/BgColor/InactiveOperator", QColor);
    defaultColorScheme->BgInactiveIdentifier = GET_SETTINGS("Editor/BgColor/InactiveIdentifier", QColor);
    defaultColorScheme->BgInactiveUnclosedString = GET_SETTINGS("Editor/BgColor/InactiveUnclosedString", QColor);
    defaultColorScheme->BgInactiveVerbatimString = GET_SETTINGS("Editor/BgColor/InactiveVerbatimString", QColor);
    defaultColorScheme->BgInactiveRegex = GET_SETTINGS("Editor/BgColor/InactiveRegex", QColor);
    defaultColorScheme->BgInactiveCommentLineDoc = GET_SETTINGS("Editor/BgColor/InactiveCommentLineDoc", QColor);
    defaultColorScheme->BgInactiveKeywordSet2 = GET_SETTINGS("Editor/BgColor/InactiveKeywordSet2", QColor);
    defaultColorScheme->BgInactiveCommentDocKeyword = GET_SETTINGS("Editor/BgColor/InactiveCommentDocKeyword", QColor);
    defaultColorScheme->BgInactiveCommentDocKeywordError = GET_SETTINGS("Editor/BgColor/InactiveCommentDocKeywordError", QColor);
    defaultColorScheme->BgInactiveGlobalClass = GET_SETTINGS("Editor/BgColor/InactiveGlobalClass", QColor);
    defaultColorScheme->BgInactiveRawString = GET_SETTINGS("Editor/BgColor/InactiveRawString", QColor);
    defaultColorScheme->BgInactiveTripleQuotedVerbatimString = GET_SETTINGS("Editor/BgColor/InactiveTripleQuotedVerbatimString", QColor);
    defaultColorScheme->BgInactiveHashQuotedString = GET_SETTINGS("Editor/BgColor/InactiveHashQuotedString", QColor);
    defaultColorScheme->BgInactivePreProcessorComment = GET_SETTINGS("Editor/BgColor/InactivePreProcessorComment", QColor);
    defaultColorScheme->BgInactivePreProcessorCommentLineDoc = GET_SETTINGS("Editor/BgColor/InactivePreProcessorCommentLineDoc", QColor);
    defaultColorScheme->BgInactiveUserLiteral = GET_SETTINGS("Editor/BgColor/InactiveUserLiteral", QColor);
    defaultColorScheme->BgInactiveTaskMarker = GET_SETTINGS("Editor/BgColor/InactiveTaskMarker", QColor);
    defaultColorScheme->BgInactiveEscapeSequence = GET_SETTINGS("Editor/BgColor/InactiveEscapeSequence", QColor);
    defaultColorScheme->BgError = GET_SETTINGS("Editor/BgColor/Error", QColor);
    defaultColorScheme->BgType = GET_SETTINGS("Editor/BgColor/Type", QColor);
    defaultColorScheme->BgPrimitiveType = GET_SETTINGS("Editor/BgColor/PrimitiveType", QColor);
    defaultColorScheme->BgWarning = GET_SETTINGS("Editor/BgColor/Warning", QColor);
    defaultColorScheme->BgWeakWarning = GET_SETTINGS("Editor/BgColor/WeakWarning", QColor);
}

void initSettingsPageForColorScheme(TpSettingsPage *page, TpColorScheme *scheme)
{
#if QT_VERSION_MAJOR <= 5
#define QColor QMetaType::Type::QColor
#else
    using enum QMetaType::Type;
#endif

    page->addEntry("Default", QColor, scheme->Default);
    page->addEntry("Comment", QColor, scheme->Comment);
    page->addEntry("CommentLine", QColor, scheme->CommentLine);
    page->addEntry("CommentDoc", QColor, scheme->CommentDoc);
    page->addEntry("Number", QColor, scheme->Number);
    page->addEntry("Keyword", QColor, scheme->Keyword);
    page->addEntry("DoubleQuotedString", QColor, scheme->DoubleQuotedString);
    page->addEntry("SingleQuotedString", QColor, scheme->SingleQuotedString);
    page->addEntry("UUID", QColor, scheme->UUID);
    page->addEntry("PreProcessor", QColor, scheme->PreProcessor);
    page->addEntry("Operator", QColor, scheme->Operator);
    page->addEntry("Identifier", QColor, scheme->Identifier);
    page->addEntry("UnclosedString", QColor, scheme->UnclosedString);
    page->addEntry("VerbatimString", QColor, scheme->VerbatimString);
    page->addEntry("Regex", QColor, scheme->Regex);
    page->addEntry("CommentLineDoc", QColor, scheme->CommentLineDoc);
    page->addEntry("KeywordSet2", QColor, scheme->KeywordSet2);
    page->addEntry("CommentDocKeyword", QColor, scheme->CommentDocKeyword);
    page->addEntry("CommentDocKeywordError", QColor, scheme->CommentDocKeywordError);
    page->addEntry("GlobalClass", QColor, scheme->GlobalClass);
    page->addEntry("RawString", QColor, scheme->RawString);
    page->addEntry("TripleQuotedVerbatimString", QColor, scheme->TripleQuotedVerbatimString);
    page->addEntry("HashQuotedString", QColor, scheme->HashQuotedString);
    page->addEntry("PreProcessorComment", QColor, scheme->PreProcessorComment);
    page->addEntry("PreProcessorCommentLineDoc", QColor, scheme->PreProcessorCommentLineDoc);
    page->addEntry("UserLiteral", QColor, scheme->UserLiteral);
    page->addEntry("TaskMarker", QColor, scheme->TaskMarker);
    page->addEntry("EscapeSequence", QColor, scheme->EscapeSequence);
    page->addEntry("InactiveDefault", QColor, scheme->InactiveDefault);
    page->addEntry("InactiveComment", QColor, scheme->InactiveComment);
    page->addEntry("InactiveCommentLine", QColor, scheme->InactiveCommentLine);
    page->addEntry("InactiveCommentDoc", QColor, scheme->InactiveCommentDoc);
    page->addEntry("InactiveNumber", QColor, scheme->InactiveNumber);
    page->addEntry("InactiveKeyword", QColor, scheme->InactiveKeyword);
    page->addEntry("InactiveDoubleQuotedString", QColor, scheme->InactiveDoubleQuotedString);
    page->addEntry("InactiveSingleQuotedString", QColor, scheme->InactiveSingleQuotedString);
    page->addEntry("InactiveUUID", QColor, scheme->InactiveUUID);
    page->addEntry("InactivePreProcessor", QColor, scheme->InactivePreProcessor);
    page->addEntry("InactiveOperator", QColor, scheme->InactiveOperator);
    page->addEntry("InactiveIdentifier", QColor, scheme->InactiveIdentifier);
    page->addEntry("InactiveUnclosedString", QColor, scheme->InactiveUnclosedString);
    page->addEntry("InactiveVerbatimString", QColor, scheme->InactiveVerbatimString);
    page->addEntry("InactiveRegex", QColor, scheme->InactiveRegex);
    page->addEntry("InactiveCommentLineDoc", QColor, scheme->InactiveCommentLineDoc);
    page->addEntry("InactiveKeywordSet2", QColor, scheme->InactiveKeywordSet2);
    page->addEntry("InactiveCommentDocKeyword", QColor, scheme->InactiveCommentDocKeyword);
    page->addEntry("InactiveCommentDocKeywordError", QColor, scheme->InactiveCommentDocKeywordError);
    page->addEntry("InactiveGlobalClass", QColor, scheme->InactiveGlobalClass);
    page->addEntry("InactiveRawString", QColor, scheme->InactiveRawString);
    page->addEntry("InactiveTripleQuotedVerbatimString", QColor, scheme->InactiveTripleQuotedVerbatimString);
    page->addEntry("InactiveHashQuotedString", QColor, scheme->InactiveHashQuotedString);
    page->addEntry("InactivePreProcessorComment", QColor, scheme->InactivePreProcessorComment);
    page->addEntry("InactivePreProcessorCommentLineDoc", QColor, scheme->InactivePreProcessorCommentLineDoc);
    page->addEntry("InactiveUserLiteral", QColor, scheme->InactiveUserLiteral);
    page->addEntry("InactiveTaskMarker", QColor, scheme->InactiveTaskMarker);
    page->addEntry("InactiveEscapeSequence", QColor, scheme->InactiveEscapeSequence);
    page->addEntry("Error", QColor, scheme->Error);
    page->addEntry("Type", QColor, scheme->Type);
    page->addEntry("PrimitiveType", QColor, scheme->PrimitiveType);
    page->addEntry("Warning", QColor, scheme->Warning);
    page->addEntry("WeakWarning", QColor, scheme->WeakWarning);

    page->addEntry("BgDefault", QColor, scheme->BgDefault);
    page->addEntry("BgComment", QColor, scheme->BgComment);
    page->addEntry("BgCommentLine", QColor, scheme->BgCommentLine);
    page->addEntry("BgCommentDoc", QColor, scheme->BgCommentDoc);
    page->addEntry("BgNumber", QColor, scheme->BgNumber);
    page->addEntry("BgKeyword", QColor, scheme->BgKeyword);
    page->addEntry("BgDoubleQuotedString", QColor, scheme->BgDoubleQuotedString);
    page->addEntry("BgSingleQuotedString", QColor, scheme->BgSingleQuotedString);
    page->addEntry("BgUUID", QColor, scheme->BgUUID);
    page->addEntry("BgPreProcessor", QColor, scheme->BgPreProcessor);
    page->addEntry("BgOperator", QColor, scheme->BgOperator);
    page->addEntry("BgIdentifier", QColor, scheme->BgIdentifier);
    page->addEntry("BgUnclosedString", QColor, scheme->BgUnclosedString);
    page->addEntry("BgVerbatimString", QColor, scheme->BgVerbatimString);
    page->addEntry("BgRegex", QColor, scheme->BgRegex);
    page->addEntry("BgCommentLineDoc", QColor, scheme->BgCommentLineDoc);
    page->addEntry("BgKeywordSet2", QColor, scheme->BgKeywordSet2);
    page->addEntry("BgCommentDocKeyword", QColor, scheme->BgCommentDocKeyword);
    page->addEntry("BgCommentDocKeywordError", QColor, scheme->BgCommentDocKeywordError);
    page->addEntry("BgGlobalClass", QColor, scheme->BgGlobalClass);
    page->addEntry("BgRawString", QColor, scheme->BgRawString);
    page->addEntry("BgTripleQuotedVerbatimString", QColor, scheme->BgTripleQuotedVerbatimString);
    page->addEntry("BgHashQuotedString", QColor, scheme->BgHashQuotedString);
    page->addEntry("BgPreProcessorComment", QColor, scheme->BgPreProcessorComment);
    page->addEntry("BgPreProcessorCommentLineDoc", QColor, scheme->BgPreProcessorCommentLineDoc);
    page->addEntry("BgUserLiteral", QColor, scheme->BgUserLiteral);
    page->addEntry("BgTaskMarker", QColor, scheme->BgTaskMarker);
    page->addEntry("BgEscapeSequence", QColor, scheme->BgEscapeSequence);
    page->addEntry("BgInactiveDefault", QColor, scheme->BgInactiveDefault);
    page->addEntry("BgInactiveComment", QColor, scheme->BgInactiveComment);
    page->addEntry("BgInactiveCommentLine", QColor, scheme->BgInactiveCommentLine);
    page->addEntry("BgInactiveCommentDoc", QColor, scheme->BgInactiveCommentDoc);
    page->addEntry("BgInactiveNumber", QColor, scheme->BgInactiveNumber);
    page->addEntry("BgInactiveKeyword", QColor, scheme->BgInactiveKeyword);
    page->addEntry("BgInactiveDoubleQuotedString", QColor, scheme->BgInactiveDoubleQuotedString);
    page->addEntry("BgInactiveSingleQuotedString", QColor, scheme->BgInactiveSingleQuotedString);
    page->addEntry("BgInactiveUUID", QColor, scheme->BgInactiveUUID);
    page->addEntry("BgInactivePreProcessor", QColor, scheme->BgInactivePreProcessor);
    page->addEntry("BgInactiveOperator", QColor, scheme->BgInactiveOperator);
    page->addEntry("BgInactiveIdentifier", QColor, scheme->BgInactiveIdentifier);
    page->addEntry("BgInactiveUnclosedString", QColor, scheme->BgInactiveUnclosedString);
    page->addEntry("BgInactiveVerbatimString", QColor, scheme->BgInactiveVerbatimString);
    page->addEntry("BgInactiveRegex", QColor, scheme->BgInactiveRegex);
    page->addEntry("BgInactiveCommentLineDoc", QColor, scheme->BgInactiveCommentLineDoc);
    page->addEntry("BgInactiveKeywordSet2", QColor, scheme->BgInactiveKeywordSet2);
    page->addEntry("BgInactiveCommentDocKeyword", QColor, scheme->BgInactiveCommentDocKeyword);
    page->addEntry("BgInactiveCommentDocKeywordError", QColor, scheme->BgInactiveCommentDocKeywordError);
    page->addEntry("BgInactiveGlobalClass", QColor, scheme->BgInactiveGlobalClass);
    page->addEntry("BgInactiveRawString", QColor, scheme->BgInactiveRawString);
    page->addEntry("BgInactiveTripleQuotedVerbatimString", QColor, scheme->BgInactiveTripleQuotedVerbatimString);
    page->addEntry("BgInactiveHashQuotedString", QColor, scheme->BgInactiveHashQuotedString);
    page->addEntry("BgInactivePreProcessorComment", QColor, scheme->BgInactivePreProcessorComment);
    page->addEntry("BgInactivePreProcessorCommentLineDoc", QColor, scheme->BgInactivePreProcessorCommentLineDoc);
    page->addEntry("BgInactiveUserLiteral", QColor, scheme->BgInactiveUserLiteral);
    page->addEntry("BgInactiveTaskMarker", QColor, scheme->BgInactiveTaskMarker);
    page->addEntry("BgInactiveEscapeSequence", QColor, scheme->BgInactiveEscapeSequence);
    page->addEntry("BgError", QColor, scheme->BgError);
    page->addEntry("BgType", QColor, scheme->BgType);
    page->addEntry("BgPrimitiveType", QColor, scheme->BgPrimitiveType);
    page->addEntry("BgWarning", QColor, scheme->BgWarning);
    page->addEntry("BgWeakWarning", QColor, scheme->BgWeakWarning);

    page->addEntry("BgLineRemoved", QColor, scheme->BgLineRemoved);
    page->addEntry("BgLineAdded", QColor, scheme->BgLineAdded);
    page->addEntry("BgLineChanged", QColor, scheme->BgLineChanged);
    page->addEntry("BgAddingPatchAdded", QColor, scheme->BgAddingPatchAdded);
    page->addEntry("BgRemovingPatchAdded", QColor, scheme->BgRemovingPatchAdded);
    page->addEntry("BgAddingPatchRemoved", QColor, scheme->BgAddingPatchRemoved);
    page->addEntry("BgRemovingPatchRemoved", QColor, scheme->BgRemovingPatchRemoved);

    page->addEntry("Special", QColor, scheme->Special);
    page->addEntry("StrongEmphasisAsterisks", QColor, scheme->StrongEmphasisAsterisks);
    page->addEntry("StrongEmphasisUnderscores", QColor, scheme->StrongEmphasisUnderscores);
    page->addEntry("EmphasisAsterisks", QColor, scheme->EmphasisAsterisks);
    page->addEntry("EmphasisUnderscores", QColor, scheme->EmphasisUnderscores);
    page->addEntry("Header1", QColor, scheme->Header1);
    page->addEntry("Header2", QColor, scheme->Header2);
    page->addEntry("Header3", QColor, scheme->Header3);
    page->addEntry("Header4", QColor, scheme->Header4);
    page->addEntry("Header5", QColor, scheme->Header5);
    page->addEntry("Header6", QColor, scheme->Header6);
    page->addEntry("Prechar", QColor, scheme->Prechar);
    page->addEntry("UnorderedListItem", QColor, scheme->UnorderedListItem);
    page->addEntry("OrderedListItem", QColor, scheme->OrderedListItem);
    page->addEntry("BlockQuote", QColor, scheme->BlockQuote);
    page->addEntry("StrikeOut", QColor, scheme->StrikeOut);
    page->addEntry("HorizontalRule", QColor, scheme->HorizontalRule);
    page->addEntry("Link", QColor, scheme->Link);
    page->addEntry("CodeBackticks", QColor, scheme->CodeBackticks);
    page->addEntry("CodeDoubleBackticks", QColor, scheme->CodeDoubleBackticks);
    page->addEntry("CodeBlock", QColor, scheme->CodeBlock);

    page->addEntry("Caret", QColor, scheme->Caret);
    page->addEntry("BgCaret", QColor, scheme->BgCaret);
    page->addEntry("IndentationGuides", QColor, scheme->IndentationGuides);
    page->addEntry("BgIndentationGuides", QColor, scheme->BgIndentationGuides);
    page->addEntry("Margin", QColor, scheme->Margin);
    page->addEntry("BgMargin", QColor, scheme->BgMargin);
    page->addEntry("Selection", QColor, scheme->Selection);
    page->addEntry("BgSelection", QColor, scheme->BgSelection);
    page->addEntry("BgFindIndicator", QColor, scheme->BgFindIndicator);
    page->addEntry("BgIncrementalIndicator", QColor, scheme->BgIncrementalIndicator);

#if QT_VERSION_MAJOR <= 5
#undef QColor
#endif
}

void updateColorScheme(TpSettingsPage *page, TpColorScheme *scheme)
{
    scheme->Default = qvariant_cast<QColor>(page->entry("Default"));
    scheme->Comment = qvariant_cast<QColor>(page->entry("Comment"));
    scheme->CommentLine = qvariant_cast<QColor>(page->entry("CommentLine"));
    scheme->CommentDoc = qvariant_cast<QColor>(page->entry("CommentDoc"));
    scheme->Number = qvariant_cast<QColor>(page->entry("Number"));
    scheme->Keyword = qvariant_cast<QColor>(page->entry("Keyword"));
    scheme->DoubleQuotedString = qvariant_cast<QColor>(page->entry("DoubleQuotedString"));
    scheme->SingleQuotedString = qvariant_cast<QColor>(page->entry("SingleQuotedString"));
    scheme->UUID = qvariant_cast<QColor>(page->entry("UUID"));
    scheme->PreProcessor = qvariant_cast<QColor>(page->entry("PreProcessor"));
    scheme->Operator = qvariant_cast<QColor>(page->entry("Operator"));
    scheme->Identifier = qvariant_cast<QColor>(page->entry("Identifier"));
    scheme->UnclosedString = qvariant_cast<QColor>(page->entry("UnclosedString"));
    scheme->VerbatimString = qvariant_cast<QColor>(page->entry("VerbatimString"));
    scheme->Regex = qvariant_cast<QColor>(page->entry("Regex"));
    scheme->CommentLineDoc = qvariant_cast<QColor>(page->entry("CommentLineDoc"));
    scheme->KeywordSet2 = qvariant_cast<QColor>(page->entry("KeywordSet2"));
    scheme->CommentDocKeyword = qvariant_cast<QColor>(page->entry("CommentDocKeyword"));
    scheme->CommentDocKeywordError = qvariant_cast<QColor>(page->entry("CommentDocKeywordError"));
    scheme->GlobalClass = qvariant_cast<QColor>(page->entry("GlobalClass"));
    scheme->RawString = qvariant_cast<QColor>(page->entry("RawString"));
    scheme->TripleQuotedVerbatimString = qvariant_cast<QColor>(page->entry("TripleQuotedVerbatimString"));
    scheme->HashQuotedString = qvariant_cast<QColor>(page->entry("HashQuotedString"));
    scheme->PreProcessorComment = qvariant_cast<QColor>(page->entry("PreProcessorComment"));
    scheme->PreProcessorCommentLineDoc = qvariant_cast<QColor>(page->entry("PreProcessorCommentLineDoc"));
    scheme->UserLiteral = qvariant_cast<QColor>(page->entry("UserLiteral"));
    scheme->TaskMarker = qvariant_cast<QColor>(page->entry("TaskMarker"));
    scheme->EscapeSequence = qvariant_cast<QColor>(page->entry("EscapeSequence"));
    scheme->InactiveDefault = qvariant_cast<QColor>(page->entry("InactiveDefault"));
    scheme->InactiveComment = qvariant_cast<QColor>(page->entry("InactiveComment"));
    scheme->InactiveCommentLine = qvariant_cast<QColor>(page->entry("InactiveCommentLine"));
    scheme->InactiveCommentDoc = qvariant_cast<QColor>(page->entry("InactiveCommentDoc"));
    scheme->InactiveNumber = qvariant_cast<QColor>(page->entry("InactiveNumber"));
    scheme->InactiveKeyword = qvariant_cast<QColor>(page->entry("InactiveKeyword"));
    scheme->InactiveDoubleQuotedString = qvariant_cast<QColor>(page->entry("InactiveDoubleQuotedString"));
    scheme->InactiveSingleQuotedString = qvariant_cast<QColor>(page->entry("InactiveSingleQuotedString"));
    scheme->InactiveUUID = qvariant_cast<QColor>(page->entry("InactiveUUID"));
    scheme->InactivePreProcessor = qvariant_cast<QColor>(page->entry("InactivePreProcessor"));
    scheme->InactiveOperator = qvariant_cast<QColor>(page->entry("InactiveOperator"));
    scheme->InactiveIdentifier = qvariant_cast<QColor>(page->entry("InactiveIdentifier"));
    scheme->InactiveUnclosedString = qvariant_cast<QColor>(page->entry("InactiveUnclosedString"));
    scheme->InactiveVerbatimString = qvariant_cast<QColor>(page->entry("InactiveVerbatimString"));
    scheme->InactiveRegex = qvariant_cast<QColor>(page->entry("InactiveRegex"));
    scheme->InactiveCommentLineDoc = qvariant_cast<QColor>(page->entry("InactiveCommentLineDoc"));
    scheme->InactiveKeywordSet2 = qvariant_cast<QColor>(page->entry("InactiveKeywordSet2"));
    scheme->InactiveCommentDocKeyword = qvariant_cast<QColor>(page->entry("InactiveCommentDocKeyword"));
    scheme->InactiveCommentDocKeywordError = qvariant_cast<QColor>(page->entry("InactiveCommentDocKeywordError"));
    scheme->InactiveGlobalClass = qvariant_cast<QColor>(page->entry("InactiveGlobalClass"));
    scheme->InactiveRawString = qvariant_cast<QColor>(page->entry("InactiveRawString"));
    scheme->InactiveTripleQuotedVerbatimString = qvariant_cast<QColor>(page->entry("InactiveTripleQuotedVerbatimString"));
    scheme->InactiveHashQuotedString = qvariant_cast<QColor>(page->entry("InactiveHashQuotedString"));
    scheme->InactivePreProcessorComment = qvariant_cast<QColor>(page->entry("InactivePreProcessorComment"));
    scheme->InactivePreProcessorCommentLineDoc = qvariant_cast<QColor>(page->entry("InactivePreProcessorCommentLineDoc"));
    scheme->InactiveUserLiteral = qvariant_cast<QColor>(page->entry("InactiveUserLiteral"));
    scheme->InactiveTaskMarker = qvariant_cast<QColor>(page->entry("InactiveTaskMarker"));
    scheme->InactiveEscapeSequence = qvariant_cast<QColor>(page->entry("InactiveEscapeSequence"));
    scheme->Error = qvariant_cast<QColor>(page->entry("Error"));
    scheme->Type = qvariant_cast<QColor>(page->entry("Type"));
    scheme->PrimitiveType = qvariant_cast<QColor>(page->entry("PrimitiveType"));
    scheme->Warning = qvariant_cast<QColor>(page->entry("Warning"));
    scheme->WeakWarning = qvariant_cast<QColor>(page->entry("WeakWarning"));

    scheme->BgDefault = qvariant_cast<QColor>(page->entry("BgDefault"));
    scheme->BgComment = qvariant_cast<QColor>(page->entry("BgComment"));
    scheme->BgCommentLine = qvariant_cast<QColor>(page->entry("BgCommentLine"));
    scheme->BgCommentDoc = qvariant_cast<QColor>(page->entry("BgCommentDoc"));
    scheme->BgNumber = qvariant_cast<QColor>(page->entry("BgNumber"));
    scheme->BgKeyword = qvariant_cast<QColor>(page->entry("BgKeyword"));
    scheme->BgDoubleQuotedString = qvariant_cast<QColor>(page->entry("BgDoubleQuotedString"));
    scheme->BgSingleQuotedString = qvariant_cast<QColor>(page->entry("BgSingleQuotedString"));
    scheme->BgUUID = qvariant_cast<QColor>(page->entry("BgUUID"));
    scheme->BgPreProcessor = qvariant_cast<QColor>(page->entry("BgPreProcessor"));
    scheme->BgOperator = qvariant_cast<QColor>(page->entry("BgOperator"));
    scheme->BgIdentifier = qvariant_cast<QColor>(page->entry("BgIdentifier"));
    scheme->BgUnclosedString = qvariant_cast<QColor>(page->entry("BgUnclosedString"));
    scheme->BgVerbatimString = qvariant_cast<QColor>(page->entry("BgVerbatimString"));
    scheme->BgRegex = qvariant_cast<QColor>(page->entry("BgRegex"));
    scheme->BgCommentLineDoc = qvariant_cast<QColor>(page->entry("BgCommentLineDoc"));
    scheme->BgKeywordSet2 = qvariant_cast<QColor>(page->entry("BgKeywordSet2"));
    scheme->BgCommentDocKeyword = qvariant_cast<QColor>(page->entry("BgCommentDocKeyword"));
    scheme->BgCommentDocKeywordError = qvariant_cast<QColor>(page->entry("BgCommentDocKeywordError"));
    scheme->BgGlobalClass = qvariant_cast<QColor>(page->entry("BgGlobalClass"));
    scheme->BgRawString = qvariant_cast<QColor>(page->entry("BgRawString"));
    scheme->BgTripleQuotedVerbatimString = qvariant_cast<QColor>(page->entry("BgTripleQuotedVerbatimString"));
    scheme->BgHashQuotedString = qvariant_cast<QColor>(page->entry("BgHashQuotedString"));
    scheme->BgPreProcessorComment = qvariant_cast<QColor>(page->entry("BgPreProcessorComment"));
    scheme->BgPreProcessorCommentLineDoc = qvariant_cast<QColor>(page->entry("BgPreProcessorCommentLineDoc"));
    scheme->BgUserLiteral = qvariant_cast<QColor>(page->entry("BgUserLiteral"));
    scheme->BgTaskMarker = qvariant_cast<QColor>(page->entry("BgTaskMarker"));
    scheme->BgEscapeSequence = qvariant_cast<QColor>(page->entry("BgEscapeSequence"));
    scheme->BgInactiveDefault = qvariant_cast<QColor>(page->entry("BgInactiveDefault"));
    scheme->BgInactiveComment = qvariant_cast<QColor>(page->entry("BgInactiveComment"));
    scheme->BgInactiveCommentLine = qvariant_cast<QColor>(page->entry("BgInactiveCommentLine"));
    scheme->BgInactiveCommentDoc = qvariant_cast<QColor>(page->entry("BgInactiveCommentDoc"));
    scheme->BgInactiveNumber = qvariant_cast<QColor>(page->entry("BgInactiveNumber"));
    scheme->BgInactiveKeyword = qvariant_cast<QColor>(page->entry("BgInactiveKeyword"));
    scheme->BgInactiveDoubleQuotedString = qvariant_cast<QColor>(page->entry("BgInactiveDoubleQuotedString"));
    scheme->BgInactiveSingleQuotedString = qvariant_cast<QColor>(page->entry("BgInactiveSingleQuotedString"));
    scheme->BgInactiveUUID = qvariant_cast<QColor>(page->entry("BgInactiveUUID"));
    scheme->BgInactivePreProcessor = qvariant_cast<QColor>(page->entry("BgInactivePreProcessor"));
    scheme->BgInactiveOperator = qvariant_cast<QColor>(page->entry("BgInactiveOperator"));
    scheme->BgInactiveIdentifier = qvariant_cast<QColor>(page->entry("BgInactiveIdentifier"));
    scheme->BgInactiveUnclosedString = qvariant_cast<QColor>(page->entry("BgInactiveUnclosedString"));
    scheme->BgInactiveVerbatimString = qvariant_cast<QColor>(page->entry("BgInactiveVerbatimString"));
    scheme->BgInactiveRegex = qvariant_cast<QColor>(page->entry("BgInactiveRegex"));
    scheme->BgInactiveCommentLineDoc = qvariant_cast<QColor>(page->entry("BgInactiveCommentLineDoc"));
    scheme->BgInactiveKeywordSet2 = qvariant_cast<QColor>(page->entry("BgInactiveKeywordSet2"));
    scheme->BgInactiveCommentDocKeyword = qvariant_cast<QColor>(page->entry("BgInactiveCommentDocKeyword"));
    scheme->BgInactiveCommentDocKeywordError = qvariant_cast<QColor>(page->entry("BgInactiveCommentDocKeywordError"));
    scheme->BgInactiveGlobalClass = qvariant_cast<QColor>(page->entry("BgInactiveGlobalClass"));
    scheme->BgInactiveRawString = qvariant_cast<QColor>(page->entry("BgInactiveRawString"));
    scheme->BgInactiveTripleQuotedVerbatimString = qvariant_cast<QColor>(page->entry("BgInactiveTripleQuotedVerbatimString"));
    scheme->BgInactiveHashQuotedString = qvariant_cast<QColor>(page->entry("BgInactiveHashQuotedString"));
    scheme->BgInactivePreProcessorComment = qvariant_cast<QColor>(page->entry("BgInactivePreProcessorComment"));
    scheme->BgInactivePreProcessorCommentLineDoc = qvariant_cast<QColor>(page->entry("BgInactivePreProcessorCommentLineDoc"));
    scheme->BgInactiveUserLiteral = qvariant_cast<QColor>(page->entry("BgInactiveUserLiteral"));
    scheme->BgInactiveTaskMarker = qvariant_cast<QColor>(page->entry("BgInactiveTaskMarker"));
    scheme->BgInactiveEscapeSequence = qvariant_cast<QColor>(page->entry("BgInactiveEscapeSequence"));
    scheme->BgError = qvariant_cast<QColor>(page->entry("BgError"));
    scheme->BgType = qvariant_cast<QColor>(page->entry("BgType"));
    scheme->BgPrimitiveType = qvariant_cast<QColor>(page->entry("BgPrimitiveType"));
    scheme->BgWarning = qvariant_cast<QColor>(page->entry("BgWarning"));
    scheme->BgWeakWarning = qvariant_cast<QColor>(page->entry("BgWeakWarning"));

    scheme->BgLineRemoved = qvariant_cast<QColor>(page->entry("BgLineRemoved"));
    scheme->BgLineAdded = qvariant_cast<QColor>(page->entry("BgLineAdded"));
    scheme->BgLineChanged = qvariant_cast<QColor>(page->entry("BgLineChanged"));
    scheme->BgAddingPatchAdded = qvariant_cast<QColor>(page->entry("BgAddingPatchAdded"));
    scheme->BgRemovingPatchAdded = qvariant_cast<QColor>(page->entry("BgRemovingPatchAdded"));
    scheme->BgAddingPatchRemoved = qvariant_cast<QColor>(page->entry("BgAddingPatchRemoved"));
    scheme->BgRemovingPatchRemoved = qvariant_cast<QColor>(page->entry("BgRemovingPatchRemoved"));

    scheme->Special = qvariant_cast<QColor>(page->entry("Special"));
    scheme->StrongEmphasisAsterisks = qvariant_cast<QColor>(page->entry("StrongEmphasisAsterisks"));
    scheme->StrongEmphasisUnderscores = qvariant_cast<QColor>(page->entry("StrongEmphasisUnderscores"));
    scheme->EmphasisAsterisks = qvariant_cast<QColor>(page->entry("EmphasisAsterisks"));
    scheme->EmphasisUnderscores = qvariant_cast<QColor>(page->entry("EmphasisUnderscores"));
    scheme->Header1 = qvariant_cast<QColor>(page->entry("Header1"));
    scheme->Header2 = qvariant_cast<QColor>(page->entry("Header2"));
    scheme->Header3 = qvariant_cast<QColor>(page->entry("Header3"));
    scheme->Header4 = qvariant_cast<QColor>(page->entry("Header4"));
    scheme->Header5 = qvariant_cast<QColor>(page->entry("Header5"));
    scheme->Header6 = qvariant_cast<QColor>(page->entry("Header6"));
    scheme->Prechar = qvariant_cast<QColor>(page->entry("Prechar"));
    scheme->UnorderedListItem = qvariant_cast<QColor>(page->entry("UnorderedListItem"));
    scheme->OrderedListItem = qvariant_cast<QColor>(page->entry("OrderedListItem"));
    scheme->BlockQuote = qvariant_cast<QColor>(page->entry("BlockQuote"));
    scheme->StrikeOut = qvariant_cast<QColor>(page->entry("StrikeOut"));
    scheme->HorizontalRule = qvariant_cast<QColor>(page->entry("HorizontalRule"));
    scheme->Link = qvariant_cast<QColor>(page->entry("Link"));
    scheme->CodeBackticks = qvariant_cast<QColor>(page->entry("CodeBackticks"));
    scheme->CodeDoubleBackticks = qvariant_cast<QColor>(page->entry("CodeDoubleBackticks"));
    scheme->CodeBlock = qvariant_cast<QColor>(page->entry("CodeBlock"));

    scheme->Caret = qvariant_cast<QColor>(page->entry("Caret"));
    scheme->BgCaret = qvariant_cast<QColor>(page->entry("BgCaret"));
    scheme->IndentationGuides = qvariant_cast<QColor>(page->entry("IndentationGuides"));
    scheme->BgIndentationGuides = qvariant_cast<QColor>(page->entry("BgIndentationGuides"));
    scheme->Margin = qvariant_cast<QColor>(page->entry("Margin"));
    scheme->BgMargin = qvariant_cast<QColor>(page->entry("BgMargin"));
    scheme->Selection = qvariant_cast<QColor>(page->entry("Selection"));
    scheme->BgSelection = qvariant_cast<QColor>(page->entry("BgSelection"));
    scheme->BgFindIndicator = qvariant_cast<QColor>(page->entry("BgFindIndicator"));
    scheme->BgIncrementalIndicator = qvariant_cast<QColor>(page->entry("BgIncrementalIndicator"));
}

TP_END_NAMESPACE
